application:
    id: magic-admin
    name: MagicAdmin
    applicationBaseNamespace: YourApplication
    applicationBaseDirectory: /var/www/html/your-application
    entityBaseNamespace: YourApplication\Data\Entity
    entityBaseDirectory: /var/www/html/your-application/inc.lib/classes
    baseIncludeDirectory: inc.app
    baseAssetDirectory: lib.assets
    composer:
        baseDirectory: inc.lib
        psr0: true
        psr4: false
        psr0BaseDirecory:
            -
                namespace: MagicAdmin
                directory: classes
        psr4BaseDirecory: null
    description: 'MagicAppBuilder Administrator'
    architecture: monolith
    baseApplicationNamespace: MagicAdmin
    baseApplicationDirectory: 'D:/xampp/htdocs/magic-admin'
    baseEntityNamespace: MagicAdmin\Entity
    baseEntityDataNamespace: MagicAdmin\Entity\Data
    baseEntityAppNamespace: MagicAdmin\Entity\App
    baseEntityDirectory: 'D:/xampp/htdocs/magic-admin/inc.lib/classes'
    baseLanguageDirectory: 'D:/xampp/htdocs/magic-admin/inc.lang'
    baseModuleDirectory:
        -
            name: root
            path: /
            active: true
    magicApp:
        version: 2.14.2
entityInfo:
    name: name
    active: active
    draft: draft
    waiting_for: waiting_for
    admin_create: admin_create
    admin_edit: admin_edit
    admin_ask_edit: admin_ask_edit
    time_create: time_create
    time_edit: time_edit
    time_ask_edit: time_ask_edit
    ip_create: ip_create
    ip_edit: ip_edit
    ip_ask_edit: ip_ask_edit
    sort_order: sort_order
    approval_id: approval_id
    approval_note: approval_note
    approval_status: approval_status
entityApvInfo:
    approval_status: approval_status
currentAction:
    user_function: $currentAction->getUserId()
    time_function: $currentAction->getTime()
    ip_function: $currentAction->getIp()
database:
    driver: sqlite
    database_file_path: 'D:/xampp/htdocs/magic-admin/inc.database/database.sqlite'
    host: ''
    port: 0
    username: ''
    password: ''
    database_name: ''
    database_schema: ''
    time_zone: Asia/Jakarta
data:
    pageSize: 20
    pageMargin: 30
    prev: '<i class="fa-solid fa-angle-left"></i>'
    next: '<i class="fa-solid fa-angle-right"></i>'
    first: '<i class="fa-solid fa-angles-left"></i>'
    last: '<i class="fa-solid fa-angles-right"></i>'
globalVariableDatabase: database
