
-- Database content
INSERT INTO license (license_id, name, license_type, description, url, allow_commercial_use, allow_modification, sort_order, admin_create, admin_edit, time_create, time_edit, ip_create, ip_edit, active) VALUES 
('apache-2.0', 'Apache License 2.0', 'Permissive', 'A permissive license with explicit patent grants. Widely used in enterprise projects.', 'https://www.apache.org/licenses/LICENSE-2.0', TRUE, TRUE, 2, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('bsd-2-clause', 'BSD 2-Clause License', 'Permissive', 'A very permissive license similar to MIT. Requires attribution.', 'https://opensource.org/licenses/BSD-2-Clause', TRUE, TRUE, 3, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('bsd-3-clause', 'BSD 3-Clause License', 'Permissive', 'Similar to BSD 2-Clause, with an additional clause prohibiting use of the project name for endorsement.', 'https://opensource.org/licenses/BSD-3-Clause', TRUE, TRUE, 4, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by', 'Creative Commons Attribution (CC BY)', 'Content License', 'Allows distribution, remix, adaptation, and commercial use, provided attribution is given.', 'https://creativecommons.org/licenses/by/4.0/', TRUE, TRUE, 20, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by-nc', 'Creative Commons Attribution-NonCommercial (CC BY-NC)', 'Content License', 'Allows remix and adaptation with attribution, but not for commercial purposes.', 'https://creativecommons.org/licenses/by-nc/4.0/', FALSE, TRUE, 23, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by-nc-nd', 'Creative Commons Attribution-NonCommercial-NoDerivatives (CC BY-NC-ND)', 'Content License', 'Most restrictive CC license: allows redistribution with attribution, but no commercial use and no modifications.', 'https://creativecommons.org/licenses/by-nc-nd/4.0/', FALSE, FALSE, 25, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by-nc-sa', 'Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)', 'Content License', 'Allows remix and adaptation with attribution, non-commercial only, and derivative works must use the same license.', 'https://creativecommons.org/licenses/by-nc-sa/4.0/', FALSE, TRUE, 24, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by-nd', 'Creative Commons Attribution-NoDerivatives (CC BY-ND)', 'Content License', 'Allows redistribution, commercial and non-commercial, as long as unchanged and with attribution.', 'https://creativecommons.org/licenses/by-nd/4.0/', TRUE, FALSE, 22, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('cc-by-sa', 'Creative Commons Attribution-ShareAlike (CC BY-SA)', 'Content License', 'Allows remixing and commercial use with attribution, but derivative works must use the same license (ShareAlike).', 'https://creativecommons.org/licenses/by-sa/4.0/', TRUE, TRUE, 21, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('epl-2.0', 'Eclipse Public License 2.0', 'Weak Copyleft', 'A weak copyleft license used mainly for Eclipse Foundation projects.', 'https://www.eclipse.org/legal/epl-2.0/', TRUE, TRUE, 10, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('gpl-2.0', 'GNU General Public License v2.0', 'Copyleft', 'Strong copyleft license that requires derivative works to also be licensed under GPL v2.', 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html', TRUE, TRUE, 5, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('gpl-3.0', 'GNU General Public License v3.0', 'Copyleft', 'Strong copyleft license that fixes loopholes in GPL v2 and includes protection against Tivoization.', 'https://www.gnu.org/licenses/gpl-3.0.html', TRUE, TRUE, 6, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('lgpl-2.1', 'GNU Lesser General Public License v2.1', 'Weak Copyleft', 'A weaker form of the GPL, allowing linking with proprietary software.', 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html', TRUE, TRUE, 7, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('lgpl-3.0', 'GNU Lesser General Public License v3.0', 'Weak Copyleft', 'Updated version of LGPL, compatible with GPL v3.', 'https://www.gnu.org/licenses/lgpl-3.0.html', TRUE, TRUE, 8, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('mit', 'MIT License', 'Permissive', 'A simple and permissive license that allows reuse with minimal restrictions. Only requires attribution.', 'https://opensource.org/licenses/MIT', TRUE, TRUE, 1, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('mpl-2.0', 'Mozilla Public License 2.0', 'Weak Copyleft', 'A weak copyleft license requiring only modified files to be shared under MPL.', 'https://www.mozilla.org/MPL/2.0/', TRUE, TRUE, 9, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('proprietary', 'Proprietary License', 'Commercial', 'A closed-source license with restrictions set by the author or company.', NULL, FALSE, FALSE, 13, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), 
('unlicense', 'The Unlicense', 'Public Domain', 'A license that dedicates works to the public domain, granting freedom without conditions.', 'https://unlicense.org/', TRUE, TRUE, 12, NULL, NULL, NULL, NULL, NULL, NULL, TRUE)
;

