-
    id: sipro-baru
    name: 'Sipro Baru'
    documentRoot: 'D:\xampp\htdocs\sipro-baru'
    author: Kamshory
    description: 'Sistem Informasi Proyek PT Perusahaan Listrik Negara (Persero)'
    selected: false
    architecture: monolith
-
    id: sipro
    name: SIPRO
    documentRoot: 'C:\PortableApps\usbwebserver\root\sipro-baru'
    author: Kamshory
    description: 'Sipro Baru'
    selected: false
    architecture: monolith
-
    id: 0673c952cb576d077460
    name: 'Music Planetbiru'
    architecture: monolith
    description: 'Music Planetbiru'
    documentRoot: 'D:/xampp/htdocs/0673c952cb576d077460'
    selected: false
-
    id: 06749b6839b630d9e33f
    name: ApplicationName
    architecture: monolith
    description: ApplicationName
    documentRoot: 'D:/xampp/htdocs/06749b6839b630d9e33f'
    selected: false
-
    id: 0674d7bd2bafbf935994
    name: ApplicationName
    architecture: ''
    description: Description
    documentRoot: 'C:/bitbucket/0674d7bd2bafbf935994'
    author: 'Your Name'
    selected: false
-
    id: musik
    name: Musik
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/musik'
    author: 'Your Name'
    selected: false
-
    id: lagu
    name: Lagu
    architecture: monolith
    description: ''
    documentRoot: 'D:/xampp/htdocs/lagu'
    author: 'Your Name'
    selected: false
-
    id: lagu2
    name: 'Music Production Manager'
    architecture: monolith
    description: ''
    documentRoot: 'D:/xampp/htdocs/lagu2'
    author: 'Your Name'
    selected: false
-
    id: sipro-gitlab
    name: 'SIPRO GITLAB'
    architecture: monolith
    description: 'Sistem Informasi Proyek PT Perusahaan Listrik Negara (Persero)'
    documentRoot: 'D:/xampp/htdocs/sipro-gitlab'
    author: Kamshory
    selected: false
-
    id: tukang
    name: Tukang
    architecture: monolith
    description: ''
    documentRoot: 'C:/bitbucket/tukang'
    author: Kamshory
    selected: false
-
    id: 0676c48e81b0c8635047
    name: ApplicationName
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/0676c48e81b0c8635047'
    author: 'Your Name'
    selected: false
-
    id: 067736eafefefbeb7030
    name: ApplicationName
    architecture: monolith
    description: ''
    documentRoot: 'C:/bitbucket/067736eafefefbeb7030'
    author: 'Your Name'
    selected: false
-
    id: 06773c4cd91d41b29c01
    name: ApplicationName
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/06773c4cd91d41b29c01'
    author: 'Your Name'
    selected: true
