-
    id: sipro-baru
    name: 'Sipro Baru'
    documentRoot: 'D:\xampp\htdocs\sipro-baru'
    author: Kamshory
    description: 'Sistem Informasi Proyek PT Perusahaan Listrik Negara (Persero)'
    selected: false
    type: fullstack
    architecture: monolith
-
    id: sipro
    name: SIPRO
    documentRoot: 'C:\PortableApps\usbwebserver\root\sipro-baru'
    author: Kamshory
    description: 'Sipro Baru'
    selected: true
    type: api
    architecture: monolith
-
    id: 0673c952cb576d077460
    name: 'Music Production Manager'
    architecture: monolith
    description: 'Music Production Manager'
    documentRoot: 'D:/xampp/htdocs/0673c952cb576d077460'
    author: Kamshory
    selected: false
