-
    id: sipro-baru
    name: 'Sipro Baru'
    documentRoot: 'D:\xampp\htdocs\sipro-baru'
    author: Kamshory
    description: 'Sistem Informasi Proyek PT Perusahaan Listrik Negara (Persero)'
    selected: false
    type: fullstack
    architecture: monolith
-
    id: sipro
    name: SIPRO
    documentRoot: 'C:\PortableApps\usbwebserver\root\sipro-baru'
    author: Kamshory
    description: 'Sipro Baru'
    selected: false
    type: api
    architecture: monolith
-
    id: 0673c952cb576d077460
    name: 'Music Planetbiru'
    architecture: monolith
    description: 'Music Planetbiru'
    documentRoot: 'D:/xampp/htdocs/0673c952cb576d077460'
    author: Kamshory
    selected: false
-
    id: 06749b6839b630d9e33f
    name: ApplicationName
    architecture: monolith
    description: ApplicationName
    documentRoot: 'D:/xampp/htdocs/06749b6839b630d9e33f'
    author: 'Your Name'
    selected: false
-
    id: 0674d7bd2bafbf935994
    name: ApplicationName
    architecture: ''
    description: Description
    documentRoot: 'C:/bitbucket/0674d7bd2bafbf935994'
    author: 'Your Name'
    selected: false
-
    id: musik
    name: Musik
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/musik'
    author: 'Your Name'
    selected: false
-
    id: lagu
    name: Lagu
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/lagu'
    author: 'Your Name'
    selected: false
-
    id: lagu2
    name: lagu2
    architecture: ''
    description: Description
    documentRoot: 'D:/xampp/htdocs/lagu2'
    author: 'Your Name'
    selected: true
