<?php

use AppBuilder\EntityInstaller\EntityApplication;
use AppBuilder\GraphQLGeneratorNodeJs;
use MagicObject\Database\PicoDatabase;
use MagicObject\SecretObject;

/**
 * Generates the README.md content for the generated Node.js project.
 *
 * @param string $appName The name of the application.
 * @param bool $withFrontend A flag indicating if the frontend is bundled with the backend.
 * @return string The generated README.md content.
 */
function generateReadmeNodeJs($appName, $withFrontend)
{
    if($withFrontend)
    {
        return "# " . $appName . "\n\n" .
        "This is a Node.js GraphQL application generated by MagicAppBuilder.\n\n" .
        "The frontend is integrated with the backend. To run the application, follow the backend setup instructions. The frontend will be available at `http://localhost:4000/`.\n";
    }
    else
    {
        return "# " . $appName . "\n\n" .
            "This is a Node.js GraphQL application generated by MagicAppBuilder.\n\n" .
            "## How to Run\n\n" .
            "1.  Ensure you have Node.js and npm installed.\n" .
            "2.  Install dependencies:\n" .
            "    ```bash\n    npm install\n    ```\n" .
            "3.  Create a `.env` file in the root directory and configure your database connection (see `.env.example` if it exists).\n" .
            "4.  Run the application:\n" .
            "    ```bash\n    npm start\n    ```\n" .
            "    For development with auto-reloading, use:\n" .
            "    ```bash\n    npm run dev\n    ```\n\n" .
            "The GraphQL endpoint will be available at `http://localhost:4000/graphql` and the GraphiQL UI at `http://localhost:4000`.\n\n"
            ;
    }
}

/**
 * Gets the Sequelize dialect for a given database driver.
 *
 * @param string $driver The database driver (e.g., 'mysql', 'pgsql').
 * @return string The corresponding Sequelize dialect.
 */
function getDatabaseDialect($driver)
{
    $dialect = '';
    // # Supported dialects: 'mysql', 'postgres', 'sqlite', 'mariadb', 'mssql'
    if ($driver == 'mysql' || $driver == 'mariadb') {
        $dialect = 'mysql';
    } else if ($driver == 'pgsql') {
        $dialect = 'postgres';
    } else if ($driver == 'sqlite') {
        $dialect = 'sqlite';
    } else if ($driver == 'sqlsrv') {
        $dialect = 'mssql';
    }
    return $dialect;
}

/**
 * Sets the database configuration for the Node.js application.
 *
 * This function reads the database settings from the application's YAML configuration file
 * and replaces placeholders in the provided .env template with these values.
 *
 * @param EntityApplication $application The application entity.
 * @param string $databaseConfiguration The .env template string.
 * @return string The populated .env configuration string.
 */
function setDatabaseConfiguration($application, $databaseConfiguration)
{
    $appConfig = new SecretObject(null);

    // Get from database
    $projectDirectory = $application->getProjectDirectory();

    $yml = $projectDirectory . "/default.yml";

    if(file_exists($yml))
    {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if($databaseConfig != null)
        {
            $databaseConfiguration = str_replace('${DB_DRIVER}', str_replace("'", "\\'", $databaseConfig->getDriver()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_HOST}', str_replace("'", "\\'", $databaseConfig->getHost()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_NAME}', str_replace("'", "\\'", $databaseConfig->getDatabaseName()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_FILE}', str_replace("'", "\\'", $databaseConfig->getDatabaseFilePath()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_USER}', str_replace("'", "\\'", $databaseConfig->getUsername()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_PASS}', str_replace("'", "\\'", $databaseConfig->getPassword()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_CHARSET}', str_replace("'", "\\'", $databaseConfig->getCharset()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_PORT}', str_replace("'", "\\'", $databaseConfig->getPort()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_TIMEZONE}', str_replace("'", "\\'", $databaseConfig->getTimeZone()), $databaseConfiguration);
            $databaseConfiguration = str_replace('${DB_DIALECT}', getDatabaseDialect($databaseConfig->getDriver()), $databaseConfiguration);
        }
    }
    return $databaseConfiguration;
}

$reservedColumnMap = createReservedColumnMap(isset($reservedColumns['columns']) ? $reservedColumns['columns'] : []);

$backendHandledColumns = getBackendHandledColumns($reservedColumnMap);

try {
    /** @var PicoDatabase $databaseBuilder */
    $application = getApplication($databaseBuilder, $applicationId); //NOSONAR

    $generator = new GraphQLGeneratorNodeJs(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        $inMemoryCache
    );

    if($withFrontend)
    {
        // --- Create a single ZIP with integrated frontend ---
        $zip = new ZipArchive();
        $zipFilePath = tempnam(sys_get_temp_dir(), 'nodejs_integrated_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create integrated ZIP file.");
        }

        // Add backend files
        $backendFiles = $generator->generate();
        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfiguration($application, $file['content']);
            }
            $zip->addFromString($file['name'], $file['content']);
        }

        // Add frontend files to 'public' directory
        $zip->addFromString('public/config/frontend-config.json', $generator->generateFrontendConfigJson());
        $zip->addFromString('public/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('public/langs/entity/source.json', $entityLanguagePacks);
        $zip->addFromString('public/langs/entity/en.json', $entityLanguagePacks);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'public/langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'public/langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'public/langs/i18n/id.json');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'public/assets');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-nodejs.js", 'public/assets/app.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-nodejs.min.js", 'public/assets/app.min.js');

        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/middleware", 'middleware');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/models/core", 'models/core');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/routes", 'routes');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/schema", 'schema');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/utils", 'utils');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/nodejs/config", 'config');

        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $application->getName(), $indexFileContent);
        $zip->addFromString('public/index.html', $indexFileContent);
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'favicon');

        // Add documentation
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);
        $appName = $application->getName();
        $manualHtml = $generator->generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);
        $zip->addFromString('README.md', generateReadmeNodeJs($appName, $withFrontend));

        $zip->close();
        $finalZipPath = $zipFilePath;
    }
    else
    {
        // --- Create Backend ZIP ---
        $backendZip = new ZipArchive();
        $backendZipFilePath = tempnam(sys_get_temp_dir(), 'backend_');
        if ($backendZip->open($backendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfiguration($application, $file['content']);
            }
            $backendZip->addFromString($file['name'], $file['content']);
        }
        $backendZip->close();

        // --- Create Frontend ZIP ---
        $frontendZip = new ZipArchive();
        $frontendZipFilePath = tempnam(sys_get_temp_dir(), 'frontend_');
        if ($frontendZip->open($frontendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create frontend ZIP file.");
        }

        $frontendZip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());
        $frontendZip->addFromString('langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $frontendZip->addFromString('langs/entity/source.json', $entityLanguagePacks);
        $frontendZip->addFromString('langs/entity/en.json', $entityLanguagePacks);
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/source.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/en.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'langs/i18n/id.json');
        addDirectoryToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'assets');
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $application->getName(), $indexFileContent);
        $frontendZip->addFromString('index.html', $indexFileContent);
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'android-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'apple-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'favicon');
        $frontendZip->close();

        // --- Create Main ZIP ---
        $mainZip = new ZipArchive();
        $mainZipFilePath = tempnam(sys_get_temp_dir(), 'main_zip_');
        if ($mainZip->open($mainZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create main ZIP file.");
        }

        $mainZip->addFile($backendZipFilePath, 'backend.zip');
        $mainZip->addFile($frontendZipFilePath, 'frontend.zip');
        $manualMd = $generator->generateManual();
        $mainZip->addFromString('manual.md', $manualMd);
        $appName = $application->getName();
        $manualHtml = $generator->generateManualHtml($manualMd, $appName);
        $mainZip->addFromString('manual.html', $manualHtml);
        $mainZip->addFromString('README.md', generateReadmeNodeJs($appName, $withFrontend));
        $mainZip->close();

        unlink($backendZipFilePath);
        unlink($frontendZipFilePath);
        $finalZipPath = $mainZipFilePath;
    }

    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $application->getApplicationId() . '-graphql-nodejs.zip"');
    header('Content-Length: ' . filesize($finalZipPath));
    readfile($finalZipPath);

    unlink($finalZipPath);
    exit();

} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}