<?php

use AppBuilder\EntityInstaller\EntityApplication;
use AppBuilder\GraphQLGeneratorGo;
use MagicObject\SecretObject;

/**
 * Sets the Go environment configuration (.env file content).
 *
 * @param EntityApplication $application The application object.
 * @param string $envTemplate The template for the .env file.
 * @return string The populated .env file content.
 */
function setGoEnvConfiguration($application, $envTemplate)
{
    $appConfig = new SecretObject(null);
    $projectDirectory = $application->getProjectDirectory();
    $yml = $projectDirectory . "/default.yml";

    if (file_exists($yml)) {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if ($databaseConfig != null) {
            $driver = $databaseConfig->getDriver();
            if($driver == 'pgsql') {
                $driver = 'postgres';
            }

            $envTemplate = str_replace('${DB_DRIVER}', $driver, $envTemplate);
            $envTemplate = str_replace('${DB_HOST}', $databaseConfig->getHost(), $envTemplate);
            $envTemplate = str_replace('${DB_PORT}', $databaseConfig->getPort(), $envTemplate);
            $envTemplate = str_replace('${DB_NAME}', $databaseConfig->getDatabaseName(), $envTemplate);
            $envTemplate = str_replace('${DB_FILE}', $databaseConfig->getDatabaseFilePath(), $envTemplate);
            $envTemplate = str_replace('${DB_USER}', $databaseConfig->getUsername(), $envTemplate);
            $envTemplate = str_replace('${DB_PASS}', $databaseConfig->getPassword(), $envTemplate);
        }
    }
    return $envTemplate;
}

/**
 * Generates the README.md content for the Go project.
 *
 * @param string $appName The name of the application.
 * @return string The content for README.md.
 */
function generateReadmeGo($appName)
{
    return "# " . $appName . "\n\n" .
        "This is a GraphQL application in Go generated by MagicAppBuilder.\n\n" .
        "## How to Run\n\n" .
        "1.  Ensure you have Go latest version installed.\n" .
        "2.  Create a `.env` file in the root directory and configure your database connection. A template is provided in `manual.md`.\n" .
        "3.  Install dependencies:\n\n" .
        "    ```bash\n" .
        "    go mod tidy\n" .
        "    ```\n\n" .
        "4.  Generate GraphQL code from the schema:\n\n" .
        "    ```bash\n" .
        "    go run github.com/99designs/gqlgen generate\n" .
        "    ```\n\n" .
        "5.  Run the application:\n\n" .
        "    ```bash\n" .
        "    go run ./\n" .
        "    ```\n\n" .
        "The GraphQL playground will be available at `http://localhost:8080/`.\n";
}

/**
 * Generate the template content for a `.env` configuration file.
 *
 * This function returns a heredoc string containing placeholder variables
 * for database configuration, server settings, and application options.
 * The returned template is intended to be used as a base for generating
 * an actual `.env` file by replacing the placeholder values with real
 * environment-specific settings.
 *
 * @return string A heredoc string containing the default `.env` template with placeholders.
 */
function getEnvTemplate()
{
        // Generate .env file content
    return <<<ENV
DB_DRIVER=\${DB_DRIVER}
DB_HOST=\${DB_HOST}
DB_PORT=\${DB_PORT}
DB_NAME=\${DB_NAME}
DB_FILE=\${DB_FILE}
DB_USER=\${DB_USER}
DB_PASS=\${DB_PASS}

SERVER_PORT=8080
SESSION_SECRET=a-very-secret-key-that-you-should-change
REQUIRE_LOGIN=true

GRAPHQL_ENDPOINT=/graphql
GRAPHQL_SCHEMA=schema/schema.graphqls
THEME_CACHE_TIME=86400

DEFAULT_LANGUAGE=en
ENV;
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);
$groupId = $builderConfig->issetGroupId() ? $builderConfig->getGroupId() : 'com.planetbiru';

$backendHandledColumns = getBackendHandledColumns($reservedColumnMap);

try {
    /** @var \MagicObject\Database\PicoDatabase $databaseBuilder */
    $app = getApplication($databaseBuilder, $applicationId);

    $moduleName = str_replace(array('-', '.', '_', ' ', '/', '\\'), '', $app->getApplicationId());

    $generator = new GraphQLGeneratorGo(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        false, // useCache is not relevant for Go in this context
        array(
            'moduleName' => $moduleName,
            'goVersion' => '1.21',
            'appName' => $app->getName(),
            'appDescription' => $app->getDescription(),
        ),
        true // requireLogin
    );

    $zip = new ZipArchive();
    $zipFilePath = tempnam(sys_get_temp_dir(), 'golang_app_');
    if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
        throw new Exception("Could not create Go project ZIP file.");
    }

    // Generate all Go files
    $backendFiles = $generator->generate();

    $envTemplate = getEnvTemplate();

    $envContent = setGoEnvConfiguration($app, $envTemplate);
    $backendFiles[] = ['name' => '.env.example', 'content' => $envTemplate];
    $backendFiles[] = ['name' => '.env', 'content' => $envContent];

    // Add all generated files to the zip
    foreach ($backendFiles as $file) {
        $zip->addFromString($file['name'], $file['content']);
    }

    // Add frontend assets (assuming they are served by the Go backend)
    // The server.go is already configured to serve from a 'static' directory.
    $staticPath = 'static';

    addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/go", '', function($zip, $filePath, $relativePath) use ($moduleName) {
        $extensions = ['go'];
        // Get file extension
        $info = pathinfo($filePath);
        $extension = $info['extension'];
        if(in_array($extension, $extensions))
        {
            $sourceData = file_get_contents($filePath);
            $fixedData = str_replace('"graphqlapplication/', '"'.$moduleName.'/', $sourceData);
            $zip->addFromString($relativePath, $fixedData);
        }
        else
        {
            $zip->addFile($filePath, $relativePath);
        }
    });

    // Add assets
    addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'static/assets');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-go.js", 'static/assets/app.js');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-go.min.js", 'static/assets/app.min.js');

    // Add language files
    $zip->addFromString('static/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
    $entityLanguagePacks = $generator->generateFrontendLanguageJson();
    $zip->addFromString('static/langs/entity/source.json', $entityLanguagePacks);
    $zip->addFromString('static/langs/entity/en.json', $entityLanguagePacks);
    $zip->addFromString('static/config/frontend-config.json', $generator->generateFrontendConfigJson());

    // Add i18n files
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/source.json');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/en.json');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'static/langs/i18n/id.json');

    // Add index.html
    $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
    $indexFileContent = str_replace('{APP_NAME}', $app->getName(), $indexFileContent);
    $zip->addFromString('static/index.html', $indexFileContent);

    // Add icon files
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'android-icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'apple-icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'favicon');

    // Add documentation
    $manualMd = $generator->generateManual();
    $zip->addFromString('manual.md', $manualMd);
    $appName = $app->getName();
    $manualHtml = $generator->generateManualHtml($manualMd, $appName);
    $zip->addFromString('manual.html', $manualHtml);
    $readmeContent = generateReadmeGo($appName);
    $zip->addFromString('README.md', $readmeContent);

    $zip->close();

    // Send the ZIP file as a download
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-go.zip"');
    header('Content-Length: ' . filesize($zipFilePath));
    readfile($zipFilePath);

    // Delete the temporary file
    unlink($zipFilePath);
    exit();

} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}