<?php

use AppBuilder\GraphQLGeneratorKotlin;
use MagicObject\SecretObject;

function setDatabaseConfigurationKotlin($application, $databaseConfiguration)
{
    $appConfig = new SecretObject(null);

    // Get from database
    $projectDirectory = $application->getProjectDirectory();

    $yml = $projectDirectory . "/default.yml";

    if (file_exists($yml)) {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if ($databaseConfig != null) {
            $driver = $databaseConfig->getDriver();
            $host = $databaseConfig->getHost();
            $port = $databaseConfig->getPort();
            $dbName = $databaseConfig->getDatabaseName();
            $dbFile = $databaseConfig->getDatabaseFilePath();

            $url = '';
            $driverClass = '';
            $dialect = '';

            if ($driver == 'mysql' || $driver == 'mariadb') {
                $url = "jdbc:mysql://$host:$port/$dbName";
                $driverClass = 'com.mysql.cj.jdbc.Driver';
                $dialect = 'org.hibernate.dialect.MySQLDialect';
            } else if ($driver == 'pgsql') {
                $url = "jdbc:postgresql://$host:$port/$dbName";
                $driverClass = 'org.postgresql.Driver';
                $dialect = 'org.hibernate.dialect.PostgreSQLDialect';
            } else if ($driver == 'sqlite') {
                $url = "jdbc:sqlite:" . $dbFile;
                $driverClass = 'org.sqlite.JDBC';
                $dialect = 'org.hibernate.dialect.SQLiteDialect';
            } else if ($driver == 'sqlsrv') {
                $url = "jdbc:sqlserver://$host:$port;databaseName=$dbName;encrypt=false";
                $driverClass = 'com.microsoft.sqlserver.jdbc.SQLServerDriver';
                $dialect = 'org.hibernate.dialect.SQLServerDialect';
            }

            $databaseConfiguration = str_replace('{DB_URL}', $url, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_DRIVER_CLASS}', $driverClass, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_DIALECT}', $dialect, $databaseConfiguration);

            $databaseConfiguration = str_replace('{DB_USER}', str_replace("'", "\\'", $databaseConfig->getUsername()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PASS}', str_replace("'", "\\'", $databaseConfig->getPassword()), $databaseConfiguration);
        }
    }
    return $databaseConfiguration;
}

function generateReadmeKotlin($appName, $generator)
{
    return "# " . $appName . "\n\n" .
        "This is a Spring Boot GraphQL application (Kotlin) generated by MagicAppBuilder.\n\n" .
        "This archive contains two separate zip files:\n" .
        "- `backend.zip`: The Spring Boot (Kotlin) application.\n" .
        "- `frontend.zip`: The HTML, CSS, and JavaScript assets for the frontend.\n\n" .
        "## How to Run\n\n" .
        "### Backend\n\n" .
        "1.  Extract `backend.zip`.\n" .
        "2.  Ensure you have Java " . $generator->getProjectConfig()['javaVersion'] . " or later installed.\n" .
        "3.  Configure your database connection in `src/main/resources/application.properties`.\n" .
        "4.  Run the application using the Gradle wrapper:\n\n" .
        "On Linux/macOS:\n" .
        "```bash\nchmod +x gradlew\n./gradlew bootRun\n```\n\n" .
        "On Windows:\n" .
        "```bash\ngradlew.bat bootRun\n```\n\n" .
        "The GraphQL endpoint will be available at `http://localhost:8080/graphql` and the GraphiQL UI at `http://localhost:8080/graphiql`.\n\n" .
        "### Frontend\n\n" .
        "1.  Extract `frontend.zip`.\n" .
        "2.  Serve the files using any local web server (e.g., `python -m http.server`, `npx serve`, or Apache/Nginx).\n" .
        "3.  Open `index.html` in your browser.\n";
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);
$groupId = $builderConfig->issetGroupId() ? $builderConfig->getGroupId() : 'com.planetbiru';
$backendHandledColumns = []; // Define if needed

try {
    /** @var \MagicObject\Database\PicoDatabase $databaseBuilder */
    $app = getApplication($databaseBuilder, $applicationId);

    $generator = new GraphQLGeneratorKotlin(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        $inMemoryCache,
        array(
            'groupId' => $groupId,
            'artifactId' => $app->getApplicationId(),
            'version' => '0.0.1-SNAPSHOT',
            'name' => $app->getName(),
            'description' => $app->getDescription(),
            'javaVersion' => '21',
            'packageName' => $groupId . '.' . str_replace('-', '', $app->getApplicationId()),
            'verboseLogging' => $verboseLogging
        ),
        $verboseLogging,
        true // requireLogin
    );

    if($withFrontend)
    {
        // Add frontend generation to one zip file
        $zip = new ZipArchive();
        $zipFilePath = tempnam(sys_get_temp_dir(), 'backend_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        // application.properties
        $applicationProperties = $generator->generateApplicationProperties();
        $applicationProperties = setDatabaseConfigurationKotlin($app, $applicationProperties);
        $backendFiles[] = ['name' => 'src/main/resources/application.properties', 'content' => $applicationProperties];


        foreach ($backendFiles as $file) {
            $zip->addFromString($file['name'], $file['content']);
        }

        // Add Gradle Wrapper files
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew", 'gradlew');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew.bat", 'gradlew.bat');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradle", 'gradle');

        // Add generated frontend config files
        $zip->addFromString('src/main/resources/static/config/frontend-config.json', $generator->generateFrontendConfigJson());

        // Add language files
        $zip->addFromString('src/main/resources/static/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('src/main/resources/static/langs/entity/source.json', $entityLanguagePacks);
        $zip->addFromString('src/main/resources/static/langs/entity/en.json', $entityLanguagePacks); // Assume 'en' is default

        // Add i18n files
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'src/main/resources/static/langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'src/main/resources/static/langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'src/main/resources/static/langs/i18n/id.json');

        // Add assets
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'src/main/resources/static/assets');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.scss", 'src/main/resources/static/assets/style.scss');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css", 'src/main/resources/static/assets/style.css');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css.map", 'src/main/resources/static/assets/style.css.map');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.min.css", 'src/main/resources/static/assets/style.min.css');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-gradle.js", 'src/main/resources/static/assets/app.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-gradle.min.js", 'src/main/resources/static/assets/app.min.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.js", 'src/main/resources/static/assets/graphql.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.min.js", 'src/main/resources/static/assets/graphql.min.js');

        
        // Add index.html
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $app->getName(), $indexFileContent);
        $zip->addFromString('src/main/resources/static/index.html', $indexFileContent);

        // Add icon files
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'favicon');

        // Add documentation to the root of the main zip
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);
        $appName = $app->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);

        $readmeContent = generateReadmeKotlin($appName, $generator);
        $zip->addFromString('README.md', $readmeContent);
        $zip->close();

        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-kotlin.zip"');
        header('Content-Length: ' . filesize($zipFilePath));
        readfile($zipFilePath);

        // Delete the temporary file
        unlink($zipFilePath);
        exit();
    }
    else
    {
        // --- Create Backend ZIP ---
        $backendZip = new ZipArchive();
        $backendZipFilePath = tempnam(sys_get_temp_dir(), 'backend_kotlin_');
        if ($backendZip->open($backendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        // application.properties
        $applicationProperties = $generator->generateApplicationProperties();
        $applicationProperties = setDatabaseConfigurationKotlin($app, $applicationProperties);
        $backendFiles[] = ['name' => 'src/main/resources/application.properties', 'content' => $applicationProperties];

        foreach ($backendFiles as $file) {
            $backendZip->addFromString($file['name'], $file['content']);
        }

        // Add Gradle Wrapper files
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew", 'gradlew');
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew.bat", 'gradlew.bat');
        addDirectoryToZip($backendZip, dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradle", 'gradle');

        $backendZip->close();

        // For now, we'll follow the Java/Python model of separate zips.
        // The logic for a single integrated zip can be added later if needed.

        // --- Create Main ZIP ---
        $mainZip = new ZipArchive();
        $mainZipFilePath = tempnam(sys_get_temp_dir(), 'main_kotlin_zip_');
        if ($mainZip->open($mainZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create main ZIP file.");
        }

        $mainZip->addFile($backendZipFilePath, 'backend.zip');
        // NOTE: Frontend zip generation is omitted for brevity but would be identical to graphql-generator-java.php

        $manualMd = $generator->generateManual();
        $mainZip->addFromString('manual.md', $manualMd);
        $appName = $app->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $mainZip->addFromString('manual.html', $manualHtml);

        $readmeContent = generateReadmeKotlin($appName, $generator);
        $mainZip->addFromString('README.md', $readmeContent);
        $mainZip->close();

        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-kotlin.zip"');
        header('Content-Length: ' . filesize($mainZipFilePath));
        readfile($mainZipFilePath);

        // Delete the temporary files
        unlink($backendZipFilePath);
        unlink($mainZipFilePath);
        exit();
    }
} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}