<?php

use AppBuilder\GraphQLGeneratorGo;
use MagicObject\SecretObject;

/**
 * Sets the Go environment configuration (.env file content).
 *
 * @param \Pico\PicoApplication $application The application object.
 * @param string $envTemplate The template for the .env file.
 * @return string The populated .env file content.
 */
function setGoEnvConfiguration($application, $envTemplate)
{
    $appConfig = new SecretObject(null);
    $projectDirectory = $application->getProjectDirectory();
    $yml = $projectDirectory . "/default.yml";

    if (file_exists($yml)) {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if ($databaseConfig != null) {
            $driver = $databaseConfig->getDriver();
            if($driver == 'pgsql') {
                $driver = 'postgres';
            }

            $envTemplate = str_replace('{DB_DRIVER}', $driver, $envTemplate);
            $envTemplate = str_replace('{DB_HOST}', $databaseConfig->getHost(), $envTemplate);
            $envTemplate = str_replace('{DB_PORT}', $databaseConfig->getPort(), $envTemplate);
            $envTemplate = str_replace('{DB_NAME}', $databaseConfig->getDatabaseName(), $envTemplate);
            $envTemplate = str_replace('{DB_USER}', $databaseConfig->getUsername(), $envTemplate);
            $envTemplate = str_replace('{DB_PASS}', $databaseConfig->getPassword(), $envTemplate);
        }
    }
    return $envTemplate;
}

/**
 * Generates the README.md content for the Go project.
 *
 * @param string $appName The name of the application.
 * @param GraphQLGeneratorGo $generator The generator instance.
 * @return string The content for README.md.
 */
function generateReadmeGo($appName, $generator)
{
    return "# " . $appName . "\n\n" .
        "This is a GraphQL application in Go generated by MagicAppBuilder.\n\n" .
        "## How to Run\n\n" .
        "1.  Ensure you have Go latest version installed.\n" .
        "2.  Create a `.env` file in the root directory and configure your database connection. A template is provided in `manual.md`.\n" .
        "3.  Install dependencies:\n\n" .
        "    ```bash\n" .
        "    go mod tidy\n" .
        "    ```\n\n" .
        "4.  Generate GraphQL code from the schema:\n\n" .
        "    ```bash\n" .
        "    go run github.com/99designs/gqlgen generate\n" .
        "    ```\n\n" .
        "5.  Run the application:\n\n" .
        "    ```bash\n" .
        "    go run ./\n" .
        "    ```\n\n" .
        "The GraphQL playground will be available at `http://localhost:8080/`.\n";
}

class ZipSimulator
{
    private $baseDirectory = '';
    public function __construct($baseDirectory)
    {
        $this->baseDirectory = $baseDirectory;
    }
    public function addFromString($fileName, $content)
    {
        $path = $this->constructPath($fileName);
        $this->prepareDirectory($path);
        file_put_contents($path, $content);
    }
    public function addFile($source, $fileName)
    {
        $path = $this->constructPath($fileName);
        $this->prepareDirectory($path);
        file_put_contents($path, file_get_contents($source));
    }
    private function constructPath($fileName)
    {
        $fileName = ltrim($fileName, "\\/");
        if(!empty($this->baseDirectory))
        {
            $path = rtrim($this->baseDirectory, "\\/")."/".ltrim($fileName);
        }
        else
        {
            $path = $fileName;
        }
        $path = str_replace(array("//", "\\\\"), "/", $path);
        return $path;
    }
    private function prepareDirectory($path)
    {
        $dirname = dirname($path);
        if(!file_exists($dirname))
        {
            mkdir($dirname, 0755, true);
        }
    }
    public function close()
    {
        // Do nothing
    }
    public function addEmptyDir($dirname)
    {
        if(!file_exists($dirname))
        {
            mkdir($dirname, 0755, true);
        }
    }
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);
$groupId = $builderConfig->issetGroupId() ? $builderConfig->getGroupId() : 'com.planetbiru';

$backendHandledColumns = [];

if (isset($reservedColumnMap['time_create'])) {
    $backendHandledColumns['timeCreate'] = ['columnName' => $reservedColumnMap['time_create'], 'type' => 'datetime'];
}
if (isset($reservedColumnMap['time_edit'])) {
    $backendHandledColumns['timeEdit'] = ['columnName' => $reservedColumnMap['time_edit'], 'type' => 'datetime'];
}
if (isset($reservedColumnMap['admin_create'])) {
    $backendHandledColumns['adminCreate'] = ['columnName' => $reservedColumnMap['admin_create'], 'type' => 'string'];
}
if (isset($reservedColumnMap['admin_edit'])) {
    $backendHandledColumns['adminEdit'] = ['columnName' => $reservedColumnMap['admin_edit'], 'type' => 'string'];
}
if (isset($reservedColumnMap['ip_create'])) {
    $backendHandledColumns['ipCreate'] = ['columnName' => $reservedColumnMap['ip_create'], 'type' => 'string'];
}
if (isset($reservedColumnMap['ip_edit'])) {
    $backendHandledColumns['ipEdit'] = ['columnName' => $reservedColumnMap['ip_edit'], 'type' => 'string'];
}

try {
    /** @var \MagicObject\Database\PicoDatabase $databaseBuilder */
    $app = getApplication($databaseBuilder, $applicationId);

    $generator = new GraphQLGeneratorGo(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        false, // useCache is not relevant for Go in this context
        array(
            'moduleName' => str_replace(array('-', '.', '_', ' ', '/', '\\'), '', $app->getApplicationId()),
            'goVersion' => '1.21',
            'appName' => $app->getName(),
            'appDescription' => $app->getDescription(),
        ),
        true // requireLogin
    );

    // Create a single ZIP file for the Go project
    // $zip = new ZipSimulator(dirname(dirname(__DIR__)) . '/go-test');
    
    $zip = new ZipArchive();
    $zipFilePath = tempnam(sys_get_temp_dir(), 'golang_app_');
    if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
        throw new Exception("Could not create Go project ZIP file.");
    }

    // Generate all Go files
    $backendFiles = $generator->generate();

    // Generate .env file content
    $envTemplate = <<<ENV
DB_DRIVER={DB_DRIVER}
DB_HOST={DB_HOST}
DB_PORT={DB_PORT}
DB_NAME={DB_NAME}
DB_USER={DB_USER}
DB_PASS={DB_PASS}

SERVER_PORT=8080
SESSION_SECRET=a-very-secret-key-that-you-should-change
REQUIRE_LOGIN=true

GRAPHQL_ENDPOINT=/graphql
GRAPHQL_SCHEMA=schema/schema.graphqls
THEME_CACHE_TIME=86400

DEFAULT_LANGUAGE=en
ENV;

    $envContent = setGoEnvConfiguration($app, $envTemplate);
    $backendFiles[] = ['name' => '.env.example', 'content' => $envTemplate];
    $backendFiles[] = ['name' => '.env', 'content' => $envContent];

    // Add all generated files to the zip
    foreach ($backendFiles as $file) {
        $zip->addFromString($file['name'], $file['content']);
    }

    // Add frontend assets (assuming they are served by the Go backend)
    // The server.go is already configured to serve from a 'static' directory.
    $staticPath = 'static';

    addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/go", '');
    
    // Add assets
    addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'static/assets');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-go.js", 'static/assets/app.js');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-go.min.js", 'static/assets/app.min.js');

    // Add language files
    $zip->addFromString('static/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
    $entityLanguagePacks = $generator->generateFrontendLanguageJson();
    $zip->addFromString('static/langs/entity/source.json', $entityLanguagePacks);
    $zip->addFromString('static/langs/entity/en.json', $entityLanguagePacks);
    $zip->addFromString('static/config/frontend-config.json', $generator->generateFrontendConfigJson());

    // Add i18n files
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/source.json');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/en.json');
    $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'static/langs/i18n/id.json');

    // Add index.html
    $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
    $indexFileContent = str_replace('{APP_NAME}', $app->getName(), $indexFileContent);
    $zip->addFromString('static/index.html', $indexFileContent);

    // Add icon files
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'android-icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'apple-icon-');
    addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", $staticPath, 'favicon');

    // Add documentation
    $manualMd = $generator->generateManual();
    $zip->addFromString('manual.md', $manualMd);
    $appName = $app->getName();
    $manualHtml = generateManualHtml($manualMd, $appName);
    $zip->addFromString('manual.html', $manualHtml);
    $readmeContent = generateReadmeGo($appName, $generator);
    $zip->addFromString('README.md', $readmeContent);

    $zip->close();

    // Send the ZIP file as a download
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-go.zip"');
    header('Content-Length: ' . filesize($zipFilePath));
    readfile($zipFilePath);

    // Delete the temporary file
    unlink($zipFilePath);
    exit();

} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}

?>