<?php

use AppBuilder\GraphQLGeneratorKotlin; // Ganti ke generator Kotlin
use MagicObject\SecretObject;

function setDatabaseConfiguration($application, $databaseConfiguration)
{
    $appConfig = new SecretObject(null);

    // Get from database
    $projectDirectory = $application->getProjectDirectory();

    $yml = $projectDirectory . "/default.yml";

    if(file_exists($yml))
    {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if($databaseConfig != null)
        {
            $driver = $databaseConfig->getDriver();
            $host = $databaseConfig->getHost();
            $port = $databaseConfig->getPort();
            $dbName = $databaseConfig->getDatabaseName();
            $dbFile = $databaseConfig->getDatabaseFilePath();

            $url = '';
            $driverClass = '';
            $dialect = '';

            if ($driver == 'mysql' || $driver == 'mariadb') {
                $url = "jdbc:mysql://$host:$port/$dbName";
                $driverClass = 'com.mysql.cj.jdbc.Driver';
                $dialect = 'org.hibernate.dialect.MySQLDialect';
            } else if ($driver == 'pgsql') {
                $url = "jdbc:postgresql://$host:$port/$dbName";
                $driverClass = 'org.postgresql.Driver';
                $dialect = 'org.hibernate.dialect.PostgreSQLDialect';
            } else if ($driver == 'sqlite') {
                $url = "jdbc:sqlite:" . $dbFile;
                $driverClass = 'org.sqlite.JDBC';
                $dialect = 'org.hibernate.dialect.SQLiteDialect';
            } else if ($driver == 'sqlsrv') {
                $url = "jdbc:sqlserver://$host:$port;databaseName=$dbName;encrypt=false";
                $driverClass = 'com.microsoft.sqlserver.jdbc.SQLServerDriver';
                $dialect = 'org.hibernate.dialect.SQLServerDialect';
            }
            
            // In pom.xml, only mysql-connector-j is included by default.
            // For other databases, the user will need to add the corresponding dependency to pom.xml.
            // For example, for PostgreSQL:
            // <dependency>
            //     <groupId>org.postgresql</groupId>
            //     <artifactId>postgresql</artifactId>
            //     <scope>runtime</scope>
            // </dependency>

            $databaseConfiguration = str_replace('{DB_URL}', $url, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_DRIVER_CLASS}', $driverClass, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_DIALECT}', $dialect, $databaseConfiguration);

            $databaseConfiguration = str_replace('{DB_USER}', str_replace("'", "\\'", $databaseConfig->getUsername()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PASS}', str_replace("'", "\\'", $databaseConfig->getPassword()), $databaseConfiguration);
        }
    }
    return $databaseConfiguration;
}

function generateReadmeKotlin($appName, $generator) // Ganti nama fungsi
{
    return "# " . $appName . "\n\n" .
        "This is a Spring Boot GraphQL application generated by MagicAppBuilder.\n\n" .
        "This archive contains two separate zip files:\n" .
        "- `backend.zip`: The Spring Boot (Kotlin) application.\n" .
        "- `frontend.zip`: The HTML, CSS, and JavaScript assets for the frontend.\n\n" .
        "## How to Run\n\n" .
        "### Backend\n\n" .
        "1.  Extract `backend.zip`.\n" .
        "1.  Ensure you have Java (JDK) " . $generator->getProjectConfig()['javaVersion'] . " or later installed.\n" .
        "2.  Configure your database connection in `src/main/resources/application.properties`.\n" .
        "3.  Run the application using the Gradle wrapper:\n\n" . // Ganti ke Gradle
        "On Linux/macOS:\n" .
        "```bash\nchmod +x mvnw\n./mvnw spring-boot:run\n```\n\n" .
        "On Windows:\n" .
        "```bash\nmvnw.cmd spring-boot:run\n```\n\n" .
        "The GraphQL endpoint will be available at `http://localhost:8080/graphql` and the GraphiQL UI at `http://localhost:8080/graphiql`.\n\n" .
        "### Frontend\n\n" .
        "1.  Extract `frontend.zip`.\n" .
        "2.  Serve the files using any local web server (e.g., `python -m http.server`, `npx serve`, or Apache/Nginx).\n" .
        "3.  Open `index.html` in your browser.\n";
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);

$groupId = $builderConfig->issetGroupId() ? $builderConfig->getGroupId() : 'com.planetbiru';

$backendHandledColumns = [];

if(isset($reservedColumnMap['time_create']))
{
    $backendHandledColumns['timeCreate'] = [
        'columnName' => $reservedColumnMap['time_create'],
        'type' => 'datetime'
    ];
}

if(isset($reservedColumnMap['time_edit']))
{
    $backendHandledColumns['timeEdit'] = [
        'columnName' => $reservedColumnMap['time_edit'],
        'type' => 'datetime'
    ];
}

if(isset($reservedColumnMap['admin_create']))
{
    $backendHandledColumns['adminCreate'] = [
        'columnName' => $reservedColumnMap['admin_create'],
        'type' => 'string'
    ];
}

if(isset($reservedColumnMap['admin_edit']))
{
    $backendHandledColumns['adminEdit'] = [
        'columnName' => $reservedColumnMap['admin_edit'],
        'type' => 'string'
    ];
}

if(isset($reservedColumnMap['ip_create']))
{
    $backendHandledColumns['ipCreate'] = [
        'columnName' => $reservedColumnMap['ip_create'],
        'type' => 'string'
    ];
}

if(isset($reservedColumnMap['ip_edit']))
{
    $backendHandledColumns['ipEdit'] = [
        'columnName' => $reservedColumnMap['ip_edit'],
        'type' => 'string'
    ];
}

try {
    /** @var \MagicObject\Database\PicoDatabase $databaseBuilder */
    $app = getApplication($databaseBuilder, $applicationId);

    $generator = new GraphQLGeneratorKotlin( // Gunakan generator Kotlin
        $schema, 
        $reservedColumns, 
        $backendHandledColumns, 
        $inMemoryCache,
        array(
            'groupId' => $groupId,
            'artifactId' => $app->getApplicationId(),
            'version' => '0.0.1-SNAPSHOT',
            'name' => $app->getName(),
            'description' => $app->getDescription(),
            'kotlinVersion' => '1.9.23', // Sesuaikan dengan versi Kotlin
            'packageName' => $groupId . '.' . str_replace('-', '', $app->getApplicationId()),
            'verboseLogging' => $verboseLogging
        ),
        $verboseLogging,
        true // requireLogin
    );

    if($withFrontend)
    {
        // Add frontend generation to one zip file
        $zip = new ZipArchive();
        $zipFilePath = tempnam(sys_get_temp_dir(), 'backend_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        // application.properties
        $applicationProperties = $generator->generateApplicationProperties();
        $applicationProperties = setDatabaseConfiguration($app, $applicationProperties);
        $backendFiles[] = ['name' => 'src/main/resources/application.properties', 'content' => $applicationProperties];


        foreach ($backendFiles as $file) {
            $zip->addFromString($file['name'], $file['content']);
        }


        // Add generated frontend config files
        $zip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());

        // Add language files
        $zip->addFromString('src/main/resources/static/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('src/main/resources/static/langs/entity/source.json', $entityLanguagePacks);
        $zip->addFromString('src/main/resources/static/langs/entity/en.json', $entityLanguagePacks); // Assume 'en' is default

        // Add i18n files
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'src/main/resources/static/langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'src/main/resources/static/langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'src/main/resources/static/langs/i18n/id.json');

        // Add assets
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'src/main/resources/static/assets');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.scss", 'src/main/resources/static/assets/style.scss');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css", 'src/main/resources/static/assets/style.css');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css.map", 'src/main/resources/static/assets/style.css.map');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.min.css", 'src/main/resources/static/assets/style.min.css');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-mvn.js", 'src/main/resources/static/assets/app.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-mvn.min.js", 'src/main/resources/static/assets/app.min.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.js", 'src/main/resources/static/assets/graphql.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.min.js", 'src/main/resources/static/assets/graphql.min.js');

        
        // Add index.html
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $app->getName(), $indexFileContent);
        $zip->addFromString('src/main/resources/static/index.html', $indexFileContent);

        // Add icon files
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'src/main/resources/static', 'favicon');


        // Add documentation to the root of the main zip
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);
        $appName = $app->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);

        $readmeContent = generateReadmeKotlin($appName, $generator); // Panggil fungsi README yang baru
        $zip->addFromString('README.md', $readmeContent);
        $zip->close();

        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-kotlin.zip"'); // Ganti nama file
        header('Content-Length: ' . filesize($zipFilePath));
        readfile($zipFilePath);

        // Delete the temporary file
        unlink($zipFilePath);
        exit();
    }
    else
    {

        // --- Create Backend ZIP ---
        $backendZip = new ZipArchive();
        $backendZipFilePath = tempnam(sys_get_temp_dir(), 'backend_');
        if ($backendZip->open($backendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        // application.properties
        $applicationProperties = $generator->generateApplicationProperties();
        $applicationProperties = setDatabaseConfiguration($app, $applicationProperties);
        $backendFiles[] = ['name' => 'src/main/resources/application.properties', 'content' => $applicationProperties];


        foreach ($backendFiles as $file) {
            $backendZip->addFromString($file['name'], $file['content']);
        }

        // Add Gradle Wrapper files to backend zip
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew", 'gradlew');
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradlew.bat", 'gradlew.bat');
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradle/wrapper/gradle-wrapper.jar", 'gradle/wrapper/gradle-wrapper.jar');
        $backendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/gradle/gradle/wrapper/gradle-wrapper.properties", 'gradle/wrapper/gradle-wrapper.properties');

        $backendZip->close();

        // --- Create Frontend ZIP ---
        $frontendZip = new ZipArchive();
        $frontendZipFilePath = tempnam(sys_get_temp_dir(), 'frontend_');
        if ($frontendZip->open($frontendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create frontend ZIP file.");
        }

        // Add generated frontend config files
        $frontendZip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());

        // Add language files
        $frontendZip->addFromString('langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $frontendZip->addFromString('langs/entity/source.json', $entityLanguagePacks);
        $frontendZip->addFromString('langs/entity/en.json', $entityLanguagePacks); // Assume 'en' is default

        // Add i18n files
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/source.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/en.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'langs/i18n/id.json');

        // Add assets
        addDirectoryToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'assets');

        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.scss", 'assets/style.scss');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css", 'assets/style.css');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.css.map", 'assets/style.css.map');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/style.min.css", 'assets/style.min.css');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-mvn.js", 'assets/app.js');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-mvn.min.js", 'assets/app.min.js');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.js", 'assets/graphql.js');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/graphql.min.js", 'assets/graphql.min.js');

         
        // Add index.html
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $app->getName(), $indexFileContent);
        $frontendZip->addFromString('index.html', $indexFileContent);

        // Add icon files
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'android-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'apple-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'favicon');

        $frontendZip->close();

        // --- Create Main ZIP ---
        $mainZip = new ZipArchive();
        $mainZipFilePath = tempnam(sys_get_temp_dir(), 'main_zip_');
        if ($mainZip->open($mainZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create main ZIP file.");
        }

        // Add backend.zip and frontend.zip to the main zip
        $mainZip->addFile($backendZipFilePath, 'backend.zip');
        $mainZip->addFile($frontendZipFilePath, 'frontend.zip');

        // Add documentation to the root of the main zip
        $manualMd = $generator->generateManual();
        $mainZip->addFromString('manual.md', $manualMd);
        $appName = $app->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $mainZip->addFromString('manual.html', $manualHtml);

        $readmeContent = generateReadmeKotlin($appName, $generator);
        $mainZip->addFromString('README.md', $readmeContent);
        $mainZip->close();

        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $app->getApplicationId() . '-graphql-kotlin.zip"');
        header('Content-Length: ' . filesize($mainZipFilePath));
        readfile($mainZipFilePath);

        // Delete the temporary file
        unlink($backendZipFilePath);
        unlink($frontendZipFilePath);
        unlink($mainZipFilePath);
        exit();
    }

} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}