<?php

use AppBuilder\EntityInstaller\EntityApplication;
use AppBuilder\GraphQLGeneratorPython;
use MagicObject\SecretObject;

/**
 * Generates the README.md content for the Python project.
 *
 * @param string $appName The name of the application.
 * @param bool $withFrontend A flag indicating whether to include frontend instructions.
 * @return string The generated README.md content.
 */
function generateReadmePython($appName, $withFrontend)
{
    $readme = "# " . $appName . "\n\n" .
        "This is a Python GraphQL application generated by MagicAppBuilder.\n\n";

    if (!$withFrontend) {
        $readme .= "This archive contains two separate zip files:\n" .
            "- `backend.zip`: The Python (FastAPI) application.\n" .
            "- `frontend.zip`: The HTML, CSS, and JavaScript assets for the frontend.\n\n";
    }

    $readme .= "## How to Run\n\n" .
        "1.  Extract the zip file.\n" .
        "2.  Ensure you have Python 3.8+ and pip installed.\n" .
        "3.  It's recommended to create a virtual environment:\n" .
        "    ```bash\n    python -m venv venv\n    source venv/bin/activate  # On Windows: venv\\Scripts\\activate\n    ```\n" .
        "4.  Install dependencies:\n" .
        "    ```bash\n    pip install -r requirements.txt\n    ```\n" .
        "5.  Create a `.env` file in the root directory and configure your database connection (see the `DATABASE_URL` format in the file).\n" .
        "6.  Run the application using Uvicorn:\n" .
        "    ```bash\n    uvicorn main:app --reload\n    ```\n\n" .
        "The GraphQL endpoint will be available at `http://localhost:8000/graphql/`.\n";

    if ($withFrontend) {
        $readme .= "\nThe frontend is integrated. Open `http://localhost:8000/` in your browser.\n";
    } else {
        $readme .= "\n### Frontend\n\n" .
            "1.  Extract `frontend.zip`.\n" .
            "2.  Serve the files using any local web server (e.g., `python -m http.server`, `npx serve`, or Apache/Nginx).\n" .
            "3.  Open `index.html` in your browser.\n";
    }
    return $readme;
}

/**
 * Sets the database configuration for the Python application.
 *
 * @param EntityApplication $application The application object.
 * @param string $databaseConfiguration The database configuration template.
 * @return string The populated database configuration.
 */
function setDatabaseConfigurationPython($application, $databaseConfiguration)
{
    $appConfig = new SecretObject(null);
    $projectDirectory = $application->getProjectDirectory();
    $yml = $projectDirectory . "/default.yml";

    if (file_exists($yml)) {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if ($databaseConfig != null) {
            $driver = $databaseConfig->getDriver();
            $host = $databaseConfig->getHost();
            $port = $databaseConfig->getPort();
            $dbName = $databaseConfig->getDatabaseName();
            $dbFile = $databaseConfig->getDatabaseFilePath();
            $user = $databaseConfig->getUsername();
            $pass = $databaseConfig->getPassword();

            $url = '';
            if ($driver == 'mysql' || $driver == 'mariadb') {
                // Requires `mysql-connector-python`

            } else if ($driver == 'pgsql') {
                // Requires `asyncpg`

            } else if ($driver == 'sqlite') {
                // Requires `aiosqlite`
            }

            $databaseConfiguration = str_replace('{DB_DRIVER}', $driver, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_HOST}', $host, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PORT}', $port, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_DATABASE}', $dbName, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_FILE}', $dbFile, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_USERNAME}', $user, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PASSWORD}', $pass, $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_ECHO}', 'True', $databaseConfiguration);
        }
    }
    return $databaseConfiguration;
}

/**
 * Sets an example database configuration for the Python application.
 *
 * @param string $databaseConfiguration The database configuration template.
 * @return string The populated example database configuration.
 */
function setDatabaseConfigurationPythonExample($databaseConfiguration)
{
    $driver = 'mysql';
    $host = 'localhost';
    $port = '3306';
    $dbName = 'your_database_name';
    $dbFile = 'your_database_file.db';
    $user = 'your_username';
    $pass = 'your_password';

    $databaseConfiguration = str_replace('{DB_DRIVER}', $driver, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_HOST}', $host, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_PORT}', $port, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_DATABASE}', $dbName, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_FILE}', $dbFile, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_USERNAME}', $user, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_PASSWORD}', $pass, $databaseConfiguration);
    $databaseConfiguration = str_replace('{DB_ECHO}', 'True', $databaseConfiguration);

    return $databaseConfiguration;
}

$reservedColumnMap = createReservedColumnMap(isset($reservedColumns['columns']) ? $reservedColumns['columns'] : []);

$backendHandledColumns = getBackendHandledColumns($reservedColumnMap);

try {
    $application = getApplication($databaseBuilder, $applicationId);

    $generator = new GraphQLGeneratorPython(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        $inMemoryCache
    );

    if($withFrontend)
    {
        // --- Create a single ZIP with integrated frontend ---
        $zip = new ZipArchive();
        $zipFilePath = tempnam(sys_get_temp_dir(), 'py_integrated_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create integrated ZIP file.");
        }

        // Add backend files
        $backendFiles = $generator->generate();

        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/backend/python", '');


        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfigurationPython($application, $file['content']);
            }
            if ($file['name'] == '.env.example') {
                $file['content'] = setDatabaseConfigurationPythonExample($file['content']);
            }
            $zip->addFromString($file['name'], $file['content']);
        }

        // Add frontend files to 'static' directory
        $zip->addFromString('static/config/frontend-config.json', $generator->generateFrontendConfigJson());
        $zip->addFromString('static/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('static/langs/entity/source.json', $entityLanguagePacks);
        $zip->addFromString('static/langs/entity/en.json', $entityLanguagePacks);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'static/langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'static/langs/i18n/id.json');


        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'static/assets');

        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $application->getName(), $indexFileContent);
        $zip->addFromString('static/index.html', $indexFileContent);
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'static', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'static', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'static', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'static', 'favicon');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-python.js", 'static/assets/app.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-python.min.js", 'static/assets/app.min.js');

        // Add documentation
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);
        $appName = $application->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);
        $zip->addFromString('README.md', generateReadmePython($appName, $withFrontend));

        $zip->close();
        $finalZipPath = $zipFilePath;
    }
    else
    {
        // --- Create Backend ZIP ---
        $backendZip = new ZipArchive();
        $backendZipFilePath = tempnam(sys_get_temp_dir(), 'backend_');
        if ($backendZip->open($backendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }

        $backendFiles = $generator->generate();

        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfigurationPython($application, $file['content']);
            }
            $backendZip->addFromString($file['name'], $file['content']);
        }
        $backendZip->close();

        // --- Create Frontend ZIP ---
        $frontendZip = new ZipArchive();
        $frontendZipFilePath = tempnam(sys_get_temp_dir(), 'frontend_');
        if ($frontendZip->open($frontendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create frontend ZIP file.");
        }

        // Add generated frontend config files
        $frontendZip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());

        // Add language files
        $frontendZip->addFromString('langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $frontendZip->addFromString('langs/entity/source.json', $entityLanguagePacks);
        $frontendZip->addFromString('langs/entity/en.json', $entityLanguagePacks);

        // Add i18n files
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/source.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/en.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'langs/i18n/id.json');

        // Add assets (using a generic app.js, you might need a specific one for Python)
        addDirectoryToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'assets');

        // Add index.html
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $application->getName(), $indexFileContent);
        $frontendZip->addFromString('index.html', $indexFileContent);

        // Add icon files
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'android-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'apple-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'favicon');

        $frontendZip->close();

        // --- Create Main ZIP ---
        $mainZip = new ZipArchive();
        $mainZipFilePath = tempnam(sys_get_temp_dir(), 'main_zip_');
        if ($mainZip->open($mainZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create main ZIP file.");
        }

        $mainZip->addFile($backendZipFilePath, 'backend.zip');
        $mainZip->addFile($frontendZipFilePath, 'frontend.zip');

        $manualMd = $generator->generateManual();
        $mainZip->addFromString('manual.md', $manualMd);
        $appName = $application->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $mainZip->addFromString('manual.html', $manualHtml);

        $readmeContent = generateReadmePython($appName, $withFrontend);
        $mainZip->addFromString('README.md', $readmeContent);
        $mainZip->close();

        unlink($backendZipFilePath);
        unlink($frontendZipFilePath);
        $finalZipPath = $mainZipFilePath;
    }

    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $application->getApplicationId() . '-graphql-python.zip"');
    header('Content-Length: ' . filesize($finalZipPath));
    readfile($finalZipPath);

    unlink($finalZipPath);
    exit();

} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}
