<?php

use AppBuilder\GraphQLGeneratorGo;
use MagicObject\SecretObject;

/**
 * Sets the database configuration for the Go project's .env file.
 *
 * @param \AppBuilder\EntityInstaller\EntityApplication $application The application entity.
 * @param string $envContent The default content of the .env file.
 * @return string The .env content with placeholders replaced.
 */
function setDatabaseConfigurationGo($application, $envContent)
{
    $appConfig = new SecretObject(null);
    $projectDirectory = $application->getProjectDirectory();
    $yml = $projectDirectory . "/default.yml";

    if (file_exists($yml)) {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if ($databaseConfig != null) { 
            $driver = $databaseConfig->getDriver();
            $dialect = 'mysql'; // Default
            if (in_array($driver, ['pgsql', 'postgresql'])) {
                $dialect = 'postgres';
            } else if ($driver == 'sqlite') {
                $dialect = 'sqlite';
            } else if ($driver == 'sqlsrv') {
                $dialect = 'sqlserver';
            }

            $envContent = str_replace('DB_DIALECT=mysql', 'DB_DIALECT=' . $dialect, $envContent);
            $envContent = str_replace('your_username', $databaseConfig->getUsername(), $envContent);
            $envContent = str_replace('your_password', $databaseConfig->getPassword(), $envContent);
            $envContent = str_replace('127.0.0.1', $databaseConfig->getHost(), $envContent);
            $envContent = str_replace('3306', $databaseConfig->getPort(), $envContent);
            $envContent = str_replace('your_database_name', $databaseConfig->getDatabaseName(), $envContent);
            $envContent = str_replace('your_database_file.db', $databaseConfig->getDatabaseFilePath(), $envContent);
        }
    }
    return $envContent;
}

/**
 * Generates the README.md file content for the Go project.
 *
 * @param string $appName The name of the application.
 * @param GraphQLGeneratorGo $generator The Go generator instance.
 * @param bool $withFrontend Whether the frontend is integrated.
 * @return string The content of the README.md file.
 */
function generateReadmeGo($appName, $generator, $withFrontend = false)
{
    /** @var GraphQLGeneratorGo $generator */
    $projectConfig = $generator->getProjectConfig();

    $readme = "";
    return "# " . $appName . "\n\n" .
        "This is a Go GraphQL application generated by MagicAppBuilder.\n\n" .
        "## How to Run\n\n" .
        "1.  **Prerequisites:**\n" .
        "    - Go (version " . $projectConfig['goVersion'] . " or newer) installed.\n" .
        "    - A running database (MySQL, PostgreSQL, SQLite, or SQL Server).\n\n" .
        "2.  **Configure Environment:**\n" .
        "    Rename `.env.example` to `.env` and fill in your database credentials.\n\n" .
        "3.  **Install Dependencies:**\n" .
        "    Open your terminal in the project root and run:\n" .
        "    ```sh\n" .
        "    go mod tidy\n" .
        "    ```\n\n" .
        "4.  **Generate GraphQL Code:**\n" .
        "    The project uses `gqlgen` to generate Go code from your GraphQL schema. Run the following command:\n" .
        "    ```sh\n" .
        "    go run github.com/99designs/gqlgen generate\n" .
        "    ```\n\n" .
        "5.  **Run the Server:**\n" .
        "    ```sh\n" .
        "    go run main.go\n" .
        "    ```\n\n" .
        "The GraphQL Playground will be available at `http://localhost:8080/graphiql`.\n" .
        ($withFrontend ? 
        "\n### Frontend\n\nThe frontend is integrated. Open `http://localhost:8080/` in your browser.\n" 
        : 
        "\n### Frontend\n\n1.  Extract `frontend.zip`.\n2.  Serve the files using any local web server.\n3.  Open `index.html` in your browser.\n"
        );
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);
$backendHandledColumns = []; // Define if needed for Go version

try {
    /** @var \MagicObject\Database\PicoDatabase $databaseBuilder */
    $application = getApplication($databaseBuilder, $applicationId);
    $appName = $application->getName();

    $generator = new GraphQLGeneratorGo(
        $schema,
        $reservedColumns,
        $backendHandledColumns,
        $inMemoryCache,
        [
            'moduleName' => $application->getApplicationId(),
            'appName' => $appName,
            'description' => $application->getDescription()
        ],
        $verboseLogging,
        true, // requireLogin
        $withFrontend
    );

    if ($withFrontend) {
        // --- Create a single ZIP with integrated frontend ---
        $zip = new ZipArchive();
        $zipFilePath = tempnam(sys_get_temp_dir(), 'go_integrated_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create integrated ZIP file.");
        }

        // Add backend files
        $backendFiles = $generator->generate();
        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfigurationGo($application, $file['content']);
                $zip->addFromString('.env.example', $file['content']);
            } else {
                $zip->addFromString($file['name'], $file['content']);
            }
        }

        // Add frontend files to 'public' directory
        $zip->addFromString('public/config/frontend-config.json', $generator->generateFrontendConfigJson());
        $zip->addFromString('public/langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('public/langs/entity/source.json', $entityLanguagePacks);
        $zip->addFromString('public/langs/entity/en.json', $entityLanguagePacks);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'public/langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'public/langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'public/langs/i18n/id.json');
        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'public/assets');
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $appName, $indexFileContent);
        $zip->addFromString('public/index.html', $indexFileContent);
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", 'public', 'favicon');

        // Add documentation
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);
        $zip->addFromString('README.md', generateReadmeGo($appName, $generator, $withFrontend));

        $zip->close();
        $finalZipPath = $zipFilePath;

    } else {
        // --- Create separate backend and frontend ZIPs ---
        // Backend ZIP
        $backendZip = new ZipArchive();
        $backendZipFilePath = tempnam(sys_get_temp_dir(), 'backend_go_');
        if ($backendZip->open($backendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create backend ZIP file.");
        }
        $backendFiles = $generator->generate();
        foreach ($backendFiles as $file) {
            if ($file['name'] == '.env') {
                $file['content'] = setDatabaseConfigurationGo($application, $file['content']);
                $backendZip->addFromString('.env.example', $file['content']);
            } else {
                $backendZip->addFromString($file['name'], $file['content']);
            }
        }
        $backendZip->close();

        // Frontend ZIP
        $frontendZip = new ZipArchive();
        $frontendZipFilePath = tempnam(sys_get_temp_dir(), 'frontend_');
        if ($frontendZip->open($frontendZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create frontend ZIP file.");
        }
        $frontendZip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());
        $frontendZip->addFromString('langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));
        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $frontendZip->addFromString('langs/entity/source.json', $entityLanguagePacks);
        $frontendZip->addFromString('langs/entity/en.json', $entityLanguagePacks);
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/source.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/en.json');
        $frontendZip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'langs/i18n/id.json');
        addDirectoryToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'assets');
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/index.html");
        $indexFileContent = str_replace('{APP_NAME}', $appName, $indexFileContent);
        $frontendZip->addFromString('index.html', $indexFileContent);
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'android-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'apple-icon-');
        addFilesWithPrefixToZip($frontendZip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'favicon');
        $frontendZip->close();

        // Main ZIP containing both
        $mainZip = new ZipArchive();
        $mainZipFilePath = tempnam(sys_get_temp_dir(), 'main_go_');
        if ($mainZip->open($mainZipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception("Could not create main ZIP file.");
        }
        $mainZip->addFile($backendZipFilePath, 'backend.zip');
        $mainZip->addFile($frontendZipFilePath, 'frontend.zip');
        $manualMd = $generator->generateManual();
        $mainZip->addFromString('manual.md', $manualMd);
        $manualHtml = generateManualHtml($manualMd, $appName);
        $mainZip->addFromString('manual.html', $manualHtml);
        $mainZip->addFromString('README.md', generateReadmeGo($appName, $generator));
        $mainZip->close();

        unlink($backendZipFilePath);
        unlink($frontendZipFilePath);
        $finalZipPath = $mainZipFilePath;
    }

    // Send the final ZIP file as a download
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $application->getApplicationId() . '-graphql-go.zip"');
    header('Content-Length: ' . filesize($finalZipPath));
    readfile($finalZipPath);

    // Delete the temporary file
    unlink($finalZipPath);
    exit();
} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}
