<?php

use AppBuilder\EntityInstaller\EntityApplication;
use AppBuilder\GraphQLGeneratorPHP;
use MagicObject\SecretObject;

/**
 * Sets the database configuration for the PHP application.
 *
 * This function reads the database settings from the application's YAML configuration file
 * and replaces placeholders in the provided database configuration template with these values.
 *
 * @param EntityApplication $application The application entity.
 * @param string $databaseConfiguration The configuration template string.
 * @return string The populated database configuration string.
 */
function setDatabaseConfiguration($application, $databaseConfiguration)
{
    $appConfig = new SecretObject(null);

    // Get from database
    $projectDirectory = $application->getProjectDirectory();

    $yml = $projectDirectory . "/default.yml";

    if(file_exists($yml))
    {
        $appConfig->loadYamlFile($yml, false, true, true);
        $databaseConfig = $appConfig->getDatabase();
        if($databaseConfig != null)
        {
            $databaseConfiguration = str_replace('{DB_DRIVER}', str_replace("'", "\\'", $databaseConfig->getDriver()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_HOST}', str_replace("'", "\\'", $databaseConfig->getHost()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_NAME}', str_replace("'", "\\'", $databaseConfig->getDatabaseName()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_FILE}', str_replace("'", "\\'", $databaseConfig->getDatabaseFilePath()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_USER}', str_replace("'", "\\'", $databaseConfig->getUsername()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PASS}', str_replace("'", "\\'", $databaseConfig->getPassword()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_CHARSET}', str_replace("'", "\\'", $databaseConfig->getCharset()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_PORT}', str_replace("'", "\\'", $databaseConfig->getPort()), $databaseConfiguration);
            $databaseConfiguration = str_replace('{DB_TIMEZONE}', str_replace("'", "\\'", $databaseConfig->getTimeZone()), $databaseConfiguration);
        }
    }
    return $databaseConfiguration;
}

/**
 * Generates the README.md content for the generated PHP project.
 *
 * @param string $appName The name of the application.
 * @param bool $withFrontend A flag indicating if the frontend is bundled with the backend.
 * @return string The generated README.md content.
 */
function generateReadmePhp($appName, $withFrontend)
{
    $readmeContent = "# " . $appName . "\n\n" .
        "This is a PHP GraphQL application generated by MagicAppBuilder.\n\n" .
        "## How to Run\n\n" .
        "### Backend\n\n" .
        "1.  Extract all files from this archive to your web server's document root (e.g., `htdocs`, `www`).\n" .
        "2.  Ensure you have PHP and Composer installed.\n" .
        "3.  Install dependencies:\n" .
        "    ```bash\n    composer install\n    ```\n" .
        "4.  Configure your database connection in `database.php`.\n" .
        "5.  The GraphQL endpoint will be available at `http://your-domain/graphql.php`.\n";

    if ($withFrontend) {
        $readmeContent .= "\n" .
            "### Frontend\n\n" .
            "1.  The frontend is integrated with the backend.\n" .
            "2.  Open `http://your-domain/index.php` in your browser.\n";
    }

    return $readmeContent;
}

$reservedColumnMap = createReservedColumnMap($reservedColumns['columns']);

$backendHandledColumns = getBackendHandledColumns($reservedColumnMap);

try {
    $application = getApplication($databaseBuilder, $applicationId);

    if($withFrontend)
    {
        $generator = new GraphQLGeneratorPHP($schema, $reservedColumns, $backendHandledColumns, $inMemoryCache);

        // Create ZIP file
        $zip = new ZipArchive();
        // Create a temporary file for the ZIP
        $zipFilePath = tempnam(sys_get_temp_dir(), 'graphql_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE) !== true) {
            throw new Exception("Could not create ZIP file.");
        }

        // Add generated code file
        $backendFiles = $generator->generate();
        foreach ($backendFiles as $file) {
            $zip->addFromString($file['name'], $file['content']);
        }

        // Add manual content file
        $manualMd = $generator->generateManual();
        $zip->addFromString('manual.md', $manualMd);

        $appName = $application->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);

        // Add frontend config files
        $zip->addFromString('config/frontend-config.json', $generator->generateFrontendConfigJson());

        // Add entity language files

        // Add language file list
        $zip->addFromString('langs/available-language.json', file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/available-language.json"));


        $entityLanguagePacks = $generator->generateFrontendLanguageJson();
        $zip->addFromString('langs/entity/source.json', $entityLanguagePacks);

        // Assumpt that default language is `en`
        $zip->addFromString('langs/entity/en.json', $entityLanguagePacks);

        // Assumpt that default language is `en`

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/source.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/en.json", 'langs/i18n/en.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/langs/i18n/id.json", 'langs/i18n/id.json');

        addDirectoryToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend/assets", 'assets');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-php.js", 'assets/app.js');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/app-php.min.js", 'assets/app.min.js');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/inc/I18n.php", 'inc/I18n.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/inc/ObjectScalar.php", 'inc/ObjectScalar.php');

        if($inMemoryCache)
        {
            $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/inc/InMemoryCache.php", 'inc/InMemoryCache.php');
        }

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/admin.php", 'admin.php');


        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/composer.json", 'composer.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/composer.lock", 'composer.lock');
        // Add all files under directory `vendor`

        $vendorPath = dirname(__DIR__) . "/inc.graphql-resources/backend/php/vendor";
        addDirectoryToZip($zip, $vendorPath, 'vendor');

        $themePath = dirname(__DIR__) . "/inc.graphql-resources/frontend/assets/themes";
        addDirectoryToZip($zip, $themePath, 'assets/themes');

        // Replace application name
        // <title>{APP_NAME}</title>
        $indexFileContent = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/index.php");
        $indexFileContent = str_replace('{APP_NAME}', $application->getName(), $indexFileContent);

        $zip->addFromString('index.php', $indexFileContent);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/language.php", 'language.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/entity-language.php", 'entity-language.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/available-language.php", 'available-language.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/available-theme.php", 'available-theme.php');

        // Get template from file
        $databaseConfiguration = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/backend/php/database.php");

        // Replace database configuration placeholders with actual values
        $databaseConfiguration = setDatabaseConfiguration($application, $databaseConfiguration);

        $zip->addFromString('database.php', $databaseConfiguration);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/sessions.php", 'sessions.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/auth.php", 'auth.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/login.php", 'login.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/logout.php", 'logout.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/frontend-config.php", 'frontend-config.php');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/message.php", "message.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/notification.php", "notification.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/user-profile.php", "user-profile.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/user-profile-update.php", "user-profile-update.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/settings.php", "settings.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/settings-update.php", "settings-update.php");
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/update-password.php", "update-password.php");

        // Add all icon files
        // Add file with prefix `icon-`
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'android-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'apple-icon-');
        addFilesWithPrefixToZip($zip, dirname(__DIR__) . "/inc.graphql-resources/frontend", '', 'favicon');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/.htaccess", '.htaccess');

        $zip->addFromString('README.md', generateReadmePhp($application->getName(), true));
        $zip->close();
        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $application->getApplicationId() . '-graphql-php.zip"');
        header('Content-Length: ' . filesize($zipFilePath));
        readfile($zipFilePath);
        // Delete the temporary file
        unlink($zipFilePath);
        exit();
    }
    else
    {
        $generator = new GraphQLGeneratorPHP($schema, $reservedColumns);

        $manualMd = $generator->generateManual();

        // Create ZIP file
        $zip = new ZipArchive();
        // Create a temporary file for the ZIP
        $zipFilePath = tempnam(sys_get_temp_dir(), 'graphql_');
        if ($zip->open($zipFilePath, ZipArchive::CREATE) !== true) {
            throw new Exception("Could not create ZIP file.");
        }

        // Get template from file
        $databaseConfiguration = file_get_contents(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/database.php");

        // Replace database configuration placeholders with actual values
        $databaseConfiguration = setDatabaseConfiguration($application, $databaseConfiguration);

        $zip->addFromString('database.php', $databaseConfiguration);
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/sessions.php", 'sessions.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/auth.php", 'auth.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/login.php", 'login.php');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/logout.php", 'logout.php');

        // Add generated code file
        $backendFiles = $generator->generate();
        foreach ($backendFiles as $file) {
            $zip->addFromString($file['name'], $file['content']);
        }
        // Add manual content file
        $zip->addFromString('manual.md', $manualMd);

        $appName = $application->getName();
        $manualHtml = generateManualHtml($manualMd, $appName);
        $zip->addFromString('manual.html', $manualHtml);

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/composer.json", 'composer.json');
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/composer.lock", 'composer.lock');

        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/frontend/php/inc/ObjectScalar.php", 'inc/ObjectScalar.php');

        if($inMemoryCache)
        {
            $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/inc/InMemoryCache.php", 'inc/InMemoryCache.php');
        }

        // Add all files under directory `vendor`
        $vendorPath = dirname(__DIR__) . "/inc.graphql-resources/backend/php/vendor";
        addDirectoryToZip($zip, $vendorPath, 'vendor');

        $zip->addFromString('README.md', generateReadmePhp($application->getName(), false));
        $zip->addFile(dirname(__DIR__) . "/inc.graphql-resources/backend/php/.htaccess", '.htaccess');

        $zip->close();
        // Send the ZIP file as a download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $application->getApplicationId() . '-graphql-php.zip"');
        header('Content-Length: ' . filesize($zipFilePath));
        readfile($zipFilePath);
        // Delete the temporary file
        unlink($zipFilePath);
        exit();
    }
} catch (Exception $e) {
    header("Content-Type: application/json");
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit();
}