<?php

namespace AppBuilder;

/**
 * The `GraphQLGeneratorKotlin` class is a powerful tool designed to automatically generate a complete Spring Boot GraphQL API in Kotlin from a JSON file that defines database entities.
 * It inspects the schema to understand tables, columns, primary keys, and foreign key relationships.
 * Based on this analysis, it produces Kotlin code for entities, repositories, DTOs, and GraphQL controllers, along with GraphQL schema files, and a comprehensive API manual in Markdown format.
 * This class streamlines the process of scaffolding a GraphQL API, reducing manual effort and ensuring consistency between the database schema and the API.
 * 
 * @package AppBuilder
 */
class GraphQLGeneratorKotlin extends GraphQLGeneratorBase
{
    /**
     * @var array<string, string> Project configuration for build.gradle.kts and package structure.
     */
    private $projectConfig = array();

    /**
     * @var bool Whether to enable verbose logging in the generated application.
     */
    private $verboseLogging = false;

    /**
     * @var bool Whether the generated application should require login.
     */
    private $requireLogin = true;

    /**
     * Constructor.
     *
     * @param array $schema Decoded JSON schema.
     * @param array|null $reservedColumns Reserved column definitions.
     * @param array $backendHandledColumns Columns handled by the backend.
     * @param bool $useCache Whether to use in-memory caching for queries.
     * @param array $projectConfig Project configuration details.
     * @param bool $verboseLogging Whether to enable verbose logging.
     * @param bool $requireLogin Whether to require login.
     * @throws \Exception
     */
    public function __construct($schema, $reservedColumns = null, $backendHandledColumns = array(), $useCache = false, $projectConfig = array(), $verboseLogging = false, $requireLogin = true)
    {
        parent::__construct($schema, $reservedColumns, $backendHandledColumns, $useCache);

        $this->projectConfig = array_merge(array(
            'groupId' => 'io.magicapp.generated',
            'artifactId' => 'graphql-app',
            'version' => '0.0.1-SNAPSHOT',
            'name' => 'GraphQL App',
            'description' => 'GraphQL API generated by MagicAppBuilder',
            'javaVersion' => '21',
            'kotlinVersion' => '1.9.23',
            'packageName' => 'io.magicapp.generated.graphqlapp',
            'verboseLogging' => $verboseLogging,
            'requireLogin' => $requireLogin
        ), $projectConfig);

        $this->verboseLogging = $verboseLogging;
        $this->requireLogin = $requireLogin;
    }

    /**
     * Maps a database type to a Kotlin type.
     *
     * @param string $dbType The database column type (e.g., VARCHAR, INT, TIMESTAMP).
     * @param ?int $length The length of the column.
     * @return string The corresponding Kotlin type string.
     */
    private function mapDbTypeToKotlinType($dbType, $length = null)
    {
        $dbType = strtolower($dbType);
        if (strpos($dbType, 'varchar') !== false || strpos($dbType, 'text') !== false) {
            return 'String?';
        }
        if (strpos($dbType, 'timestamp') !== false || strpos($dbType, 'datetime') !== false) {
            return 'java.time.LocalDateTime?';
        }
        if (strpos($dbType, 'date') !== false) {
            return 'java.time.LocalDate?';
        }
        if (strpos($dbType, 'decimal') !== false || strpos($dbType, 'float') !== false || strpos($dbType, 'double') !== false) {
            return 'Double?';
        }
        if ((strpos($dbType, 'tinyint') !== false && isset($length) && $length == '1') || strpos($dbType, 'bool') !== false || strpos($dbType, 'bit') !== false) {
            return 'Boolean?';
        }
        if (strpos($dbType, 'int') !== false) {
            return 'Int?';
        }
        return 'String?'; // Default fallback
    }

    /**
     * Maps a Kotlin type to a GraphQL type.
     *
     * @param string $kotlinType The Kotlin type.
     * @return string The corresponding GraphQL type.
     */
    private function mapKotlinTypeToGqlType($kotlinType)
    {
        $baseType = str_replace('?', '', $kotlinType);
        switch ($baseType) {
            case 'Int':
                return 'Int';
            case 'Double':
            case 'Float':
                return 'Float';
            case 'Boolean':
                return 'Boolean';
            case 'String':
            case 'java.time.LocalDate':
            case 'java.time.LocalDateTime':
                return 'String'; // Or custom scalars
            default:
                return 'String';
        }
    }

    /**
     * Main function to generate all files for the Spring Boot project.
     *
     * @param bool $withFrontend Deprecated parameter, not used.
     * @return array An array of file definitions, each with 'name' and 'content'.
     */
    public function generate()
    {
        $files = array();
        $packagePath = 'src/main/kotlin/' . str_replace('.', '/', $this->projectConfig['packageName']);

        // 1. Gradle build files
        $files[] = ['name' => 'build.gradle.kts', 'content' => $this->generateBuildGradleKts()];
        $files[] = ['name' => 'settings.gradle.kts', 'content' => $this->generateSettingsGradleKts()];
        $files[] = ['name' => 'gradle', 'content' => $this->generateGradle()];
        $files[] = ['name' => 'gradle.bat', 'content' => $this->generateGradleBat()];
        $files[] = ['name' => 'gradle/wrapper/gradle-wrapper.properties', 'content' => $this->generateGradleWrapper()];


        // 2. Main Application Class
        $files[] = ['name' => $packagePath . '/' . $this->pascalCase($this->projectConfig['artifactId']) . 'Application.kt', 'content' => $this->generateMainAppClass()];

        // 3. GraphQL Schema, Entities, Repositories, DTOs, Controllers
        $allSchemaParts = array();
        $allQueryFields = array();
        $allMutationFields = array();

        foreach ($this->analyzedSchema as $tableName => $tableInfo) {
            // Generate individual Kotlin files
            $files[] = ['name' => $packagePath . '/model/entity/' . ucfirst($this->camelCase($tableName)) . '.kt', 'content' => $this->generateEntityClass($tableName, $tableInfo)];
            $files[] = ['name' => $packagePath . '/model/repository/' . ucfirst($this->camelCase($tableName)) . 'Repository.kt', 'content' => $this->generateRepositoryInterface($tableName, $tableInfo)];
            $files[] = ['name' => $packagePath . '/model/dto/' . ucfirst($this->camelCase($tableName)) . 'Input.kt', 'content' => $this->generateDtoClass($tableName, $tableInfo)];
            $files[] = ['name' => $packagePath . '/controller/' . ucfirst($this->camelCase($tableName)) . 'Controller.kt', 'content' => $this->generateControllerClass($tableName, $tableInfo)];

            // Collect schema parts to be merged later
            $schemaParts = $this->getSchemaPartsForTable($tableName, $tableInfo);
            $allSchemaParts[] = $schemaParts['types'];
            $allQueryFields[] = $schemaParts['queries'];
            $allMutationFields[] = $schemaParts['mutations'];
        }

        // 4. Utility classes
        $files[] = ['name' => $packagePath . '/util/SpecificationBuilder.kt', 'content' => $this->generateSpecificationBuilder()];
        $files[] = ['name' => $packagePath . '/util/FilterCriteria.kt', 'content' => $this->generateFilterCriteria()];
        $files[] = ['name' => $packagePath . '/util/SearchOperation.kt', 'content' => $this->generateSearchOperation()];
        $files[] = ['name' => $packagePath . '/util/GenericSpecification.kt', 'content' => $this->generateGenericSpecification()];

        // 5. DTOs for GraphQL inputs
        $files[] = ['name' => $packagePath . '/model/dto/FilterInput.kt', 'content' => $this->generateFilterInputDto()];
        $files[] = ['name' => $packagePath . '/model/dto/SortInput.kt', 'content' => $this->generateSortInputDto()];

        // 6. Combined GraphQL schema file
        $files[] = ['name' => 'src/main/resources/graphql/schema.graphqls', 'content' => $this->generateCombinedSchema($allSchemaParts, $allQueryFields, $allMutationFields)];

        // 7. Security and Auth files
        $files[] = ['name' => $packagePath . '/config/SecurityConfig.kt', 'content' => $this->generateSecurityConfig()];
        $files[] = ['name' => $packagePath . '/config/CorsConfig.kt', 'content' => $this->generateCorsConfig()];
        $files[] = ['name' => $packagePath . '/config/Sha1PasswordEncoder.kt', 'content' => $this->generateSha1PasswordEncoder()];
        $files[] = ['name' => $packagePath . '/service/JpaUserDetailsService.kt', 'content' => $this->generateUserDetailsService()];
        $files[] = ['name' => $packagePath . '/model/entity/Admin.kt', 'content' => $this->generateAdminEntity()];
        $files[] = ['name' => $packagePath . '/model/repository/AdminRepository.kt', 'content' => $this->generateAdminRepository()];

        // 8. Auth and App Controllers
        $files[] = ['name' => $packagePath . '/controller/dto/LoginRequest.kt', 'content' => $this->generateLoginRequestDto()];
        $files[] = ['name' => $packagePath . '/controller/dto/LoginResponse.kt', 'content' => $this->generateLoginResponseDto()];
        $files[] = ['name' => $packagePath . '/controller/AuthController.kt', 'content' => $this->generateAuthController()];

        return $files;
    }

    /**
     * Generates the application.properties file.
     *
     * @return string The content of application.properties.
     */
    public function generateApplicationProperties()
    {
        $requireLoginValue = $this->requireLogin ? 'true' : 'false';
        return <<<PROPERTIES
spring.application.name={$this->projectConfig['name']}

# Database Configuration (Please update with your details)
app.security.require-login=$requireLoginValue

# CORS Configuration (Cross-Origin Resource Sharing)
app.security.cors.enabled=true
app.security.cors.allowed-origins=http://localhost,http://127.0.0.1,http://localhost:3000,http://localhost:8080

spring.datasource.url={DB_URL}
spring.datasource.username={DB_USER}
spring.datasource.password={DB_PASS}
spring.datasource.driver-class-name={DB_DRIVER_CLASS}

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect={DB_DIALECT}

# Use database column names directly without converting to camelCase
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.schema.file-extensions=.graphqls

PROPERTIES;
    }

    /**
     * Generates the build.gradle.kts file.
     *
     * @return string The content of the build.gradle.kts file.
     */
    private function generateBuildGradleKts()
    {
        $config = $this->projectConfig;
        return <<<GRADLE
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "3.2.5"
	id("io.spring.dependency-management") version "1.1.4"
	kotlin("jvm") version "{$config['kotlinVersion']}"
	kotlin("plugin.spring") version "{$config['kotlinVersion']}"
	kotlin("plugin.jpa") version "{$config['kotlinVersion']}"
}

group = "{$config['groupId']}"
version = "{$config['version']}"

java {
	sourceCompatibility = JavaVersion.VERSION_{$config['javaVersion']}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-graphql")
	implementation("org.springframework.boot:spring-boot-starter-security")
	implementation("org.springframework.boot.boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")

	// Database Drivers
	runtimeOnly("com.mysql:mysql-connector-j")
    runtimeOnly("org.mariadb.jdbc:mariadb-java-client")
    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("com.microsoft.sqlserver:mssql-jdbc")
    runtimeOnly("org.xerial:sqlite-jdbc")

	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testImplementation("org.springframework:spring-webflux")
	testImplementation("org.springframework.graphql:spring-graphql-test")
	testImplementation("org.springframework.security:spring-security-test")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xjsr305=strict"
		jvmTarget = "{$config['javaVersion']}"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}

GRADLE;
    }

    /**
     * Generates the settings.gradle.kts file.
     *
     * @return string The content of the settings.gradle.kts file.
     */
    private function generateSettingsGradleKts()
    {
        $artifactId = $this->projectConfig['artifactId'];
        return "rootProject.name = \"$artifactId\"\n";
    }

    /**
     * Generates the main Spring Boot application class in Kotlin.
     *
     * @return string The content of the main application class.
     */
    private function generateMainAppClass()
    {
        $className = $this->pascalCase($this->projectConfig['artifactId']) . 'Application';
        $packageName = $this->projectConfig['packageName'];
        $cachingAnnotation = $this->useCache ? "@EnableCaching" : "";

        $useCaseImport = $this->useCache ? "import org.springframework.cache.annotation.EnableCaching\n" : "";

        return <<<KOTLIN
package $packageName

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
{$useCaseImport}
$cachingAnnotation
@SpringBootApplication
class $className

fun main(args: Array<String>) {
	runApplication<$className>(*args)
}
KOTLIN;
    }

    /**
     * Generates the Kotlin entity data class for a given table.
     * @param string $tableName The name of the database table.
     * @param array $tableInfo The information about the table's columns.
     *
     * @return string The content of the entity class.
     */
    private function generateEntityClass($tableName, $tableInfo)
    {
        $className = ucfirst($this->camelCase($tableName));
        $package = $this->projectConfig['packageName'];

        $imports = "import jakarta.persistence.*\nimport java.io.Serializable\n";
        $fields = "";
        $hasLdt = false;
        $hasLd = false;

        foreach ($tableInfo['columns'] as $colName => $colInfo) {
            $kotlinType = $this->mapDbTypeToKotlinType($colInfo['type'], $colInfo['length']);
            $fieldName = $this->camelCase($colName);

            if (strpos($kotlinType, 'LocalDateTime') !== false) $hasLdt = true;
            if (strpos($kotlinType, 'LocalDate') !== false) $hasLd = true;

            $annotations = "";
            if ($colInfo['isPrimaryKey']) {
                $annotations .= "    @Id\n";
                if ($colInfo['isAutoIncrement']) {
                    $annotations .= "    @GeneratedValue(strategy = GenerationType.IDENTITY)\n";
                }
            }
            if ($fieldName !== $colName) {
                $annotations .= "    @Column(name = \"$colName\")\n";
            }
            $fixedKotlinType = basename(str_replace(['\\', '.'], '/', $kotlinType));
            $fields .= "$annotations    var $fieldName: {$fixedKotlinType} = null\n\n";
        }

        if ($hasLdt) $imports .= "import java.time.LocalDateTime\n";
        if ($hasLd) $imports .= "import java.time.LocalDate\n";

        return <<<KOTLIN
package $package.model.entity

$imports
@Entity
@Table(name = "$tableName")
data class $className(
$fields) : Serializable
KOTLIN;
    }

    /**
     * Generates the Kotlin repository interface for a given table.
     * @param string $tableName The name of the database table.
     * @param array $tableInfo The information about the table's columns.
     *
     * @return string The content of the repository interface.
     */
    private function generateRepositoryInterface($tableName, $tableInfo)
    {
        $className = ucfirst($this->camelCase($tableName));
        $package = $this->projectConfig['packageName'];
        $pkKotlinType = 'String';
        foreach ($tableInfo['columns'] as $col) {
            if ($col['isPrimaryKey']) {
                $pkKotlinType = str_replace('?', '', $this->mapDbTypeToKotlinType($col['type'], $col['length']));
                break;
            }
        }

        $imports = "import org.springframework.data.jpa.repository.JpaRepository\n";
        $imports .= "import org.springframework.data.jpa.repository.JpaSpecificationExecutor\n";
        $imports .= "import $package.model.entity.$className\n";
        if ($this->useCache) {
            $imports .= "import org.springframework.cache.annotation.Cacheable\n";
        }
        $imports .= "import java.util.Optional\n";

        $findByIdMethod = "override fun findById(id: $pkKotlinType): Optional<$className>";
        if ($this->useCache) {
            $findByIdMethod = "@Cacheable(value = \"{$this->camelCase($tableName)}\", key = \"#id\")\n    " . $findByIdMethod;
        }

        return <<<KOTLIN
package $package.model.repository

$imports
import org.springframework.stereotype.Repository

@Repository
interface {$className}Repository : JpaRepository<$className, $pkKotlinType>, JpaSpecificationExecutor<$className> {
    $findByIdMethod
}
KOTLIN;
    }

    /**
     * Generates the DTO data class for a given table.
     * @param string $tableName The name of the database table.
     * @param array $tableInfo The information about the table's columns.
     *
     * @return string The content of the DTO class.
     */
    private function generateDtoClass($tableName, $tableInfo)
    {
        $className = ucfirst($this->camelCase($tableName)) . "Input";
        $package = $this->projectConfig['packageName'];

        $imports = "";
        $fields = "";
        $hasLdt = false;
        $hasLd = false;

        foreach ($tableInfo['columns'] as $colName => $colInfo) {
            if ($colName === $tableInfo['primaryKey'] && ($colInfo['isAutoIncrement'] || $colInfo['primaryKeyValue'] == 'autogenerated')) {
                continue;
            }
            $kotlinType = $this->mapDbTypeToKotlinType($colInfo['type'], $colInfo['length']);
            $fieldName = $this->camelCase($colName);
            if (strpos($kotlinType, 'LocalDateTime') !== false) $hasLdt = true;
            if (strpos($kotlinType, 'LocalDate') !== false) $hasLd = true;
            $fixedKotlinType = basename(str_replace(['\\', '.'], '/', $kotlinType));
            $fields .= "    var $fieldName: $fixedKotlinType = null,\n";
        }

        if ($hasLdt) $imports .= "import java.time.LocalDateTime\n";
        if ($hasLd) $imports .= "import java.time.LocalDate\n";
        $field = rtrim($fields, ",\n");
        return <<<KOTLIN
package $package.model.dto

$imports
data class $className(
$field
)
KOTLIN;
    }

    /**
     * Generates the Controller class for a given table.
     * @param string $tableName The name of the database table.
     * @param array $tableInfo The information about the table's columns.
     *
     * @return string The content of the Controller class.
     */
    private function generateControllerClass($tableName, $tableInfo)
    {
        $camelName = $this->camelCase($tableName);
        $ucCamelName = ucfirst($camelName);
        $pluralCamelName = $this->pluralize($camelName);
        $package = $this->projectConfig['packageName'];
        $pkKotlinType = 'String';
        foreach ($tableInfo['columns'] as $col) {
            if ($col['isPrimaryKey']) {
                $pkKotlinType = str_replace('?', '', $this->mapDbTypeToKotlinType($col['type'], $col['length']));
                break;
            }
        }

        return <<<KOTLIN
package $package.controller

import $package.model.dto.FilterInput
import $package.model.dto.SortInput
import $package.model.dto.{$ucCamelName}Input
import $package.model.entity.$ucCamelName
import $package.model.repository.{$ucCamelName}Repository
import $package.util.QueryUtil
import org.springframework.beans.BeanUtils
import org.springframework.data.domain.Page
import org.springframework.graphql.data.method.annotation.Argument
import org.springframework.graphql.data.method.annotation.MutationMapping
import org.springframework.graphql.data.method.annotation.QueryMapping
import org.springframework.stereotype.Controller

@Controller
class {$ucCamelName}Controller(private val {$camelName}Repository: {$ucCamelName}Repository) {

    @QueryMapping
    fun {$camelName}(@Argument id: $pkKotlinType): $ucCamelName? {
        return {$camelName}Repository.findById(id).orElse(null)
    }

    @QueryMapping
    fun {$pluralCamelName}(
        @Argument limit: Int?,
        @Argument offset: Int?,
        @Argument page: Int?,
        @Argument size: Int?,
        @Argument orderBy: List<SortInput>?,
        @Argument filter: List<FilterInput>?
    ): Map<String, Any> {
        val pageable = QueryUtil.createPageable(limit, offset, page, size, orderBy)
        val specification = QueryUtil.createSpecification<$ucCamelName>(filter)
        val resultPage: Page<$ucCamelName> = {$camelName}Repository.findAll(specification, pageable)
        return QueryUtil.createPageResultMap(resultPage)
    }

    @MutationMapping
    fun create{$ucCamelName}(@Argument input: {$ucCamelName}Input): $ucCamelName {
        val entity = $ucCamelName()
        BeanUtils.copyProperties(input, entity)
        // Additional logic for creation can be added here
        return {$camelName}Repository.save(entity)
    }

    @MutationMapping
    fun update{$ucCamelName}(@Argument id: $pkKotlinType, @Argument input: {$ucCamelName}Input): $ucCamelName {
        val entity = {$camelName}Repository.findById(id)
            .orElseThrow { RuntimeException("$ucCamelName not found with id \$id") }
        BeanUtils.copyProperties(input, entity)
        // Additional logic for update can be added here
        return {$camelName}Repository.save(entity)
    }

    @MutationMapping
    fun delete{$ucCamelName}(@Argument id: $pkKotlinType): Boolean {
        {$camelName}Repository.deleteById(id)
        return true
    }
}
KOTLIN;
    }

    /**
     * Generates the GraphQL schema parts for a given table.
     * @param string $tableName The name of the table.
     * @param array $tableInfo The table information.
     *
     * @return array An array containing 'types', 'queries', and 'mutations' strings.
     */
    private function getSchemaPartsForTable($tableName, $tableInfo)
    {
        $camelName = $this->camelCase($tableName);
        $ucCamelName = ucfirst($camelName);
        $pluralCamelName = $this->pluralize($camelName);

        // Type fields
        $fields = "";
        foreach ($tableInfo['columns'] as $colName => $colInfo) {
            $kotlinType = $this->mapDbTypeToKotlinType($colInfo['type'], $colInfo['length']);
            $gqlType = $this->mapKotlinTypeToGqlType($kotlinType);
            $fieldName = $this->camelCase($colName);
            $fields .= "    $fieldName: $gqlType\n";
        }

        // Input fields
        $inputFields = "";
        foreach ($tableInfo['columns'] as $colName => $colInfo) {
            if ($colName === $tableInfo['primaryKey'] && ($colInfo['isAutoIncrement'] || $colInfo['primaryKeyValue'] == 'autogenerated')) {
                continue;
            }
            $kotlinType = $this->mapDbTypeToKotlinType($colInfo['type'], $colInfo['length']);
            $gqlType = $this->mapKotlinTypeToGqlType($kotlinType);
            $fieldName = $this->camelCase($colName);
            $inputFields .= "    $fieldName: $gqlType\n";
        }

        $types = <<<GQL
type $ucCamelName {
$fields}

input {$ucCamelName}Input {
$inputFields}

type {$ucCamelName}Page {
    items: [$ucCamelName],
    total: Int,
    limit: Int,
    page: Int,
    totalPages: Int,
    hasNext: Boolean,
    hasPrevious: Boolean
}
GQL;

        $pkKotlinType = $this->mapDbTypeToKotlinType($tableInfo['columns'][$tableInfo['primaryKey']]['type'], $tableInfo['columns'][$tableInfo['primaryKey']]['length']);
        $pkGqlType = $this->mapKotlinTypeToGqlType($pkKotlinType);

        $queries = "    {$camelName}(id: {$pkGqlType}!): $ucCamelName\n";
        $queries .= "    {$pluralCamelName}(limit: Int, offset: Int, page: Int, size: Int, orderBy: [SortInput], filter: [FilterInput]): {$ucCamelName}Page\n";

        $mutations = "    create{$ucCamelName}(input: {$ucCamelName}Input!): $ucCamelName\n";
        $mutations .= "    update{$ucCamelName}(id: {$pkGqlType}!, input: {$ucCamelName}Input!): $ucCamelName\n";
        $mutations .= "    delete{$ucCamelName}(id: {$pkGqlType}!): Boolean\n";

        return [
            'types' => $types,
            'queries' => $queries,
            'mutations' => $mutations
        ];
    }

    /**
     * Combines all schema parts into a single GraphQL schema string.
     * @param array $allSchemaParts Array of type definitions.
     * @param array $allQueryFields Array of query definitions.
     * @param array $allMutationFields Array of mutation definitions.
     *
     * @return string The complete GraphQL schema.
     */
    private function generateCombinedSchema($allSchemaParts, $allQueryFields, $allMutationFields)
    {
        $typesString = implode("\n", $allSchemaParts);
        $queriesString = implode("", $allQueryFields);
        $mutationsString = implode("", $allMutationFields);

        return <<<GQL
enum SortDirection {
    ASC
    DESC
}

enum FilterOperator {
    EQUALS
    NOT_EQUALS
    CONTAINS
    GREATER_THAN
    GREATER_THAN_OR_EQUALS
    LESS_THAN
    LESS_THAN_OR_EQUALS
    IN
    NOT_IN
}

input SortInput {
    field: String!
    direction: SortDirection
}

input FilterInput {
    field: String!
    value: String
    operator: FilterOperator
}

$typesString

type Query {
$queriesString}

type Mutation {
$mutationsString}
GQL;
    }

    /**
     * Generates a markdown manual with examples for all queries and mutations.
     *
     * @param bool $withFrontend Deprecated parameter, not used.
     * @return string The markdown content.
     */
    public function generateManual()
    {
        $manualContent = "# Kotlin GraphQL API Manual\r\n\r\n";
        $manualContent .= "This document provides examples for all available queries and mutations for your Spring Boot application.\r\n\r\n";

        $manualContent .= "## Dependencies\r\n\r\n";
        $manualContent .= "All required dependencies are defined in the `build.gradle.kts` file. Gradle will handle downloading them automatically.\r\n\r\n";

        $manualContent .= "## Database Connection\r\n\r\n";
        $manualContent .= "This API requires a database connection. You must configure the `src/main/resources/application.properties` file. Here is an example for connecting to a MySQL database:\r\n\r\n";
        $manualContent .= "```properties\r\n";
        $manualContent .= "spring.application.name=YourAppName\r\n\r\n";
        $manualContent .= "# Database Configuration (Please update with your details)\r\n";
        $manualContent .= "app.security.require-login=true\r\n\r\n";
        $manualContent .= "# CORS Configuration (Cross-Origin Resource Sharing)\r\n";
        $manualContent .= "app.security.cors.enabled=true\r\n";
        $manualContent .= "app.security.cors.allowed-origins=http://localhost,http://127.0.0.1,http://localhost:3000,http://localhost:8080\r\n\r\n";
        $manualContent .= "spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name\r\n";
        $manualContent .= "spring.datasource.username=your_username\r\n";
        $manualContent .= "spring.datasource.password=your_password\r\n";
        $manualContent .= "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\n\r\n";
        $manualContent .= "# JPA/Hibernate Configuration\r\n";
        $manualContent .= "spring.jpa.hibernate.ddl-auto=update\r\n";
        $manualContent .= "spring.jpa.show-sql=true\r\n";
        $manualContent .= "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect\r\n";
        $manualContent .= "spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl\r\n\r\n";
        $manualContent .= "# GraphQL Properties\r\n";
        $manualContent .= "spring.graphql.graphiql.enabled=true\r\n";
        $manualContent .= "spring.graphql.schema.locations=classpath:graphql/\r\n";
        $manualContent .= "spring.graphql.schema.file-extensions=.graphqls\r\n";
        $manualContent .= "```\r\n\r\n";
        $manualContent .= "Make sure to replace `your_database_name`, `your_username`, and `your_password` with your actual database credentials.\r\n\r\n";

        $manualContent .= "---\r\n\r\n";

        foreach ($this->analyzedSchema as $tableName => $tableInfo) {
            $camelName = $this->camelCase($tableName);
            $pluralCamelName = $this->pluralize($camelName);
            $ucCamelName = ucfirst($camelName);

            $manualContent .= "## " . $ucCamelName . "\r\n\r\n";

            // --- Get Fields for examples ---
            $fieldsString = $this->getFieldsForManual($tableInfo, false);
            $mutationFieldsString = $this->getFieldsForManual($tableInfo, true); // No relations for mutation return

            // --- Query Examples ---
            $manualContent .= "### Queries\r\n\r\n";

            // Get Single Item
            $manualContent .= "#### Get a single " . $camelName . "\r\n\r\n";
            $manualContent .= "```graphql\r\n";
            $manualContent .= "query Get" . $ucCamelName . " {\r\n";
            $manualContent .= "  " . $camelName . "(id: \"your-" . $camelName . "-id\") {\r\n";
            $manualContent .= $fieldsString;
            $manualContent .= "  }\r\n";
            $manualContent .= "}\r\n";
            $manualContent .= "```\r\n\r\n";

            // Get List
            $manualContent .= "#### Get a list of " . $pluralCamelName . " (with filter & sort)\r\n\r\n";
            $manualContent .= "Supports `limit`, `offset`, `orderBy`, and `filter`.\r\n\r\n";

            $filterField = $this->camelCase($tableInfo['primaryKey']);
            $filterValue = '"your-' . $camelName . '-id"';
            $filterOperator = 'EQUALS';

            foreach ($tableInfo['columns'] as $columnName => $columnInfo) {
                if (($columnName === 'name' || $columnName === 'title') && !$columnInfo['isForeignKey']) {
                    $filterField = $this->camelCase($columnName);
                    $filterValue = '"some-text"';
                    $filterOperator = 'CONTAINS';
                    break;
                }
            }

            $manualContent .= "```graphql\r\n";
            $manualContent .= "query Get" . ucfirst($pluralCamelName) . " {\r\n";
            $manualContent .= "  " . $pluralCamelName . "(\r\n    limit: 10, \r\n    offset: 0, \r\n    orderBy: [{field: \"" . $this->camelCase($tableInfo['primaryKey']) . "\", direction: DESC}],\r\n    filter: [{field: \"" . $filterField . "\", value: " . $filterValue . ", operator: " . $filterOperator . "}]\r\n  ) {\r\n";
            $manualContent .= "    items {\r\n";
            $manualContent .= preg_replace('/^/m', '      ', $fieldsString); // Indent fields
            $manualContent .= "    }\r\n";
            $manualContent .= "    total\r\n";
            $manualContent .= "    limit\r\n";
            $manualContent .= "    page\r\n";
            $manualContent .= "    totalPages\r\n";
            $manualContent .= "    hasNext\r\n";
            $manualContent .= "    hasPrevious\r\n";
            $manualContent .= "  }\r\n";
            $manualContent .= "}\r\n";
            $manualContent .= "```\r\n\r\n";

            // --- Mutation Examples ---
            $manualContent .= "### Mutations\r\n\r\n";

            list(, $inputExampleString) = $this->getInputFieldsForManual($tableInfo);

            // Create
            $manualContent .= "#### Create a new " . $camelName . "\r\n\r\n";
            $manualContent .= "```graphql\r\n";
            $manualContent .= "mutation Create" . $ucCamelName . " {\r\n";
            $manualContent .= "  create" . $ucCamelName . "(input: {\r\n" . $inputExampleString . "  }) {\r\n";
            $manualContent .= $mutationFieldsString;
            $manualContent .= "  }\r\n";
            $manualContent .= "}\r\n";
            $manualContent .= "```\r\n\r\n";

            // Update
            $manualContent .= "#### Update an existing " . $camelName . "\r\n\r\n";
            $manualContent .= "```graphql\r\n";
            $manualContent .= "mutation Update" . $ucCamelName . " {\r\n";
            $manualContent .= "  update" . $ucCamelName . "(id: \"your-" . $camelName . "-id\", input: {\r\n" . $inputExampleString . "  }) {\r\n";
            $manualContent .= $mutationFieldsString;
            $manualContent .= "  }\r\n";
            $manualContent .= "}\r\n";
            $manualContent .= "```\r\n\r\n";

            // Delete
            $manualContent .= "#### Delete a " . $camelName . "\r\n\r\n";
            $manualContent .= "Returns `true` on success.\r\n\r\n";
            $manualContent .= "```graphql\r\n";
            $manualContent .= "mutation Delete" . $ucCamelName . " {\r\n";
            $manualContent .= "  delete" . $ucCamelName . "(id: \"your-" . $camelName . "-id\")\r\n";
            $manualContent .= "}\r\n";
            $manualContent .= "```\r\n\r\n";
        }

        // --- API Reference Guide ---
        $manualContent .= "## API Reference Guide\r\n\r\n";
        $manualContent .= "This section provides a reference for common arguments used in list queries.\r\n\r\n";

        // Filtering
        $manualContent .= "### Filtering (`filter`)\r\n\r\n";
        $manualContent .= "The `filter` argument allows you to narrow down results based on field values. It accepts a list of filter objects, which are combined with `AND` logic.\r\n\r\n";
        $manualContent .= "| Operator       | Description                                      | Example                                                |\r\n";
        $manualContent .= "|----------------|--------------------------------------------------|--------------------------------------------------------|\r\n";
        $manualContent .= "| `EQUALS`       | Finds records where the field exactly matches the value. | `{field: \"status\", value: \"published\"}`                |\r\n";
        $manualContent .= "| `NOT_EQUALS`   | Finds records where the field does not match the value. | `{field: \"status\", value: \"archived\", operator: NOT_EQUALS}` |\r\n";
        $manualContent .= "| `CONTAINS`     | Finds records where the text field contains the value (`LIKE '%value%'`). | `{field: \"title\", value: \"love\", operator: CONTAINS}` |\r\n";
        $manualContent .= "| `GREATER_THAN_OR_EQUALS` | Finds records where the numeric/date field is greater than or equal to the value. | `{field: \"price\", value: \"99.99\", operator: GREATER_THAN_OR_EQUALS}` |\r\n";
        $manualContent .= "| `GREATER_THAN` | Finds records where the numeric/date field is greater than the value. | `{field: \"price\", value: \"100\", operator: GREATER_THAN}` |\r\n";
        $manualContent .= "| `LESS_THAN_OR_EQUALS`    | Finds records where the numeric/date field is less than or equal to the value. | `{field: \"stock\", value: \"10\", operator: LESS_THAN_OR_EQUALS}`   |\r\n";
        $manualContent .= "| `LESS_THAN`    | Finds records where the numeric/date field is less than the value. | `{field: \"stock\", value: \"10\", operator: LESS_THAN}`   |\r\n";
        $manualContent .= "| `IN` / `NOT_IN` | Finds records where the field value is in (or not in) a comma-separated list of values. | `{field: \"categoryId\", value: \"1,2,3\", operator: IN}` |\r\n\r\n";

        // Sorting
        $manualContent .= "### Sorting (`orderBy`)\r\n\r\n";
        $manualContent .= "The `orderBy` argument sorts the results. It accepts a list of sort objects.\r\n\r\n";
        $manualContent .= "- `field`: The name of the field to sort by (e.g., `\"name\"`).\r\n";
        $manualContent .= "- `direction`: The sort direction. Can be `ASC` (ascending) or `DESC` (descending). Defaults to `ASC`.\r\n\r\n";
        $manualContent .= "**Example:** `orderBy: [{field: \"releaseDate\", direction: DESC}]`\r\n\r\n";

        // Pagination
        $manualContent .= "### Pagination (`limit` & `offset` or `page` & `size`)\r\n\r\n";
        $manualContent .= "- `limit` / `size`: Specifies the maximum number of records to return.\r\n";
        $manualContent .= "- `offset` / `page`: Specifies the starting point of the records.\r\n\r\n";
        $manualContent .= "**Example:** To get the second page of 10 items: `limit: 10, offset: 10` or `page: 2, size: 10`\r\n\r\n";

        return $manualContent;
    }

    //<editor-fold desc="Utility and Config Generators">

    /**
     * Get project configuration.
     *
     * @return array<string, string>
     */
    public function getProjectConfig()
    {
        return $this->projectConfig;
    }

    /**
     * Generates the SpecificationBuilder.kt file.
     * @return string
     */
    private function generateSpecificationBuilder()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.util

import org.springframework.data.jpa.domain.Specification

class SpecificationBuilder<T> {
    private val params: MutableList<FilterCriteria> = mutableListOf()

    fun with(key: String, operation: SearchOperation, value: Any): SpecificationBuilder<T> {
        params.add(FilterCriteria(key, operation, value))
        return this
    }

    fun build(): Specification<T>? {
        if (params.isEmpty()) {
            return null
        }

        val specs = params.map { GenericSpecification<T>(it) }
        var result = specs[0]

        for (i in 1 until params.size) {
            result = Specification.where(result).and(specs[i])
        }
        return result
    }
}
KOTLIN;
    }

    /**
     * Generates the FilterCriteria.kt file.
     * @return string
     */
    private function generateFilterCriteria()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.util

data class FilterCriteria(
    val key: String,
    val operation: SearchOperation,
    val value: Any?
)
KOTLIN;
    }

    /**
     * Generates the SearchOperation.kt file.
     * @return string
     */
    private function generateSearchOperation()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.util

enum class SearchOperation {
    EQUALS,
    NOT_EQUALS,
    CONTAINS,
    GREATER_THAN,
    GREATER_THAN_OR_EQUALS,
    LESS_THAN,
    LESS_THAN_OR_EQUALS,
    IN,
    NOT_IN
}
KOTLIN;
    }

    /**
     * Generates the GenericSpecification.kt file.
     * @return string
     */
    private function generateGenericSpecification()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.util

import jakarta.persistence.criteria.CriteriaBuilder
import jakarta.persistence.criteria.CriteriaQuery
import jakarta.persistence.criteria.Predicate
import jakarta.persistence.criteria.Root
import org.springframework.data.jpa.domain.Specification

class GenericSpecification<T>(private val criteria: FilterCriteria) : Specification<T> {

    override fun toPredicate(root: Root<T>, query: CriteriaQuery<*>, builder: CriteriaBuilder): Predicate? {
        val key = criteria.key
        val value = criteria.value
        val fieldType = root.get<Any>(key).javaType

        val typedValue = value?.let {
            val stringValue = it.toString()
            when (fieldType) {
                Integer::class.java, Int::class.java -> stringValue.toIntOrNull()
                Long::class.java, Long::class.java -> stringValue.toLongOrNull()
                Double::class.java, Double::class.java -> stringValue.toDoubleOrNull()
                Float::class.java, Float::class.java -> stringValue.toFloatOrNull()
                Boolean::class.java, Boolean::class.java -> stringValue.toBoolean()
                else -> stringValue
            }
        }

        return when (criteria.operation) {
            SearchOperation.EQUALS -> builder.equal(root.get<Any>(key), typedValue)
            SearchOperation.NOT_EQUALS -> builder.notEqual(root.get<Any>(key), typedValue)
            SearchOperation.GREATER_THAN -> builder.greaterThan(root.get(key), typedValue.toString())
            SearchOperation.GREATER_THAN_OR_EQUALS -> builder.greaterThanOrEqualTo(root.get(key), typedValue.toString())
            SearchOperation.LESS_THAN -> builder.lessThan(root.get(key), typedValue.toString())
            SearchOperation.LESS_THAN_OR_EQUALS -> builder.lessThanOrEqualTo(root.get(key), typedValue.toString())
            SearchOperation.CONTAINS -> if (fieldType == String::class.java) builder.like(root.get(key), "%\$typedValue%") else builder.equal(root.get(key), typedValue)
            SearchOperation.IN -> root.get<Any>(key).`in`(typedValue as? Collection<*>)
            SearchOperation.NOT_IN -> builder.not(root.get<Any>(key).`in`(typedValue as? Collection<*>))
        }
    }
}
KOTLIN;
    }

    /**
     * Generates the FilterInput.kt DTO file.
     * @return string
     */
    private function generateFilterInputDto()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.model.dto

data class FilterInput(
    val field: String,
    val value: String?,
    val operator: String?
)
KOTLIN;
    }

    /**
     * Generates the SortInput.kt DTO file.
     * @return string
     */
    private function generateSortInputDto()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.model.dto

data class SortInput(
    val field: String,
    val direction: String = "ASC"
)
KOTLIN;
    }

    /**
     * Generates the SecurityConfig.kt file.
     * @return string
     */
    private function generateSecurityConfig()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.config

import $package.service.JpaUserDetailsService
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.http.HttpStatus
import org.springframework.security.config.annotation.web.builders.HttpSecurity
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity
import org.springframework.security.config.http.SessionCreationPolicy
import org.springframework.security.web.SecurityFilterChain
import org.springframework.security.web.authentication.HttpStatusEntryPoint

@Configuration
@EnableWebSecurity
class SecurityConfig(private val userDetailsService: JpaUserDetailsService) {

    @Value("\${app.security.require-login:true}")
    private val requireLogin: Boolean = true

    @Bean
    fun passwordEncoder(): Sha1PasswordEncoder {
        return Sha1PasswordEncoder()
    }

    @Bean
    @Throws(Exception::class)
    fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
        http.csrf { it.disable() }

        if (!requireLogin) {
            http.authorizeHttpRequests { it.anyRequest().permitAll() }
                .sessionManagement { it.sessionCreationPolicy(SessionCreationPolicy.STATELESS) }
        } else {
            http.authorizeHttpRequests { auth ->
                auth.requestMatchers("/login", "/logout", "/graphiql/**", "/vendor/**").permitAll()
                    .anyRequest().authenticated()
            }
            .userDetailsService(userDetailsService)
            .exceptionHandling { it.authenticationEntryPoint(HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED)) }
            .logout { it.disable() } // Custom logout in AuthController
        }

        return http.build()
    }
}
KOTLIN;
    }

    /**
     * Generates the CorsConfig.kt file.
     * @return string
     */
    private function generateCorsConfig()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.config

import org.springframework.beans.factory.annotation.Value
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.web.servlet.config.annotation.CorsRegistry
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer

@Configuration
class CorsConfig {

    @Value("\${app.security.cors.allowed-origins:}")
    private lateinit var allowedOrigins: Array<String>

    @Bean
    @ConditionalOnProperty(name = ["app.security.cors.enabled"], havingValue = "true")
    fun corsConfigurer(): WebMvcConfigurer {
        return object : WebMvcConfigurer {
            override fun addCorsMappings(registry: CorsRegistry) {
                registry.addMapping("/**")
                        .allowedOrigins(*allowedOrigins)
                        .allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS")
                        .allowedHeaders("*")
                        .allowCredentials(true)
            }
        }
    }
}
KOTLIN;
    }

    /**
     * Generates the Sha1PasswordEncoder.kt file.
     * @return string
     */
    private function generateSha1PasswordEncoder()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.config

import org.springframework.security.crypto.password.PasswordEncoder
import java.math.BigInteger
import java.security.MessageDigest

class Sha1PasswordEncoder : PasswordEncoder {

    override fun encode(rawPassword: CharSequence): String {
        return sha1(sha1(rawPassword.toString()))
    }

    override fun matches(rawPassword: CharSequence, encodedPassword: String): Boolean {
        return encodedPassword == encode(rawPassword)
    }

    fun sha1(input: String): String {
        val md = MessageDigest.getInstance("SHA-1")
        val messageDigest = md.digest(input.toByteArray())
        val no = BigInteger(1, messageDigest)
        var hashtext = no.toString(16)
        while (hashtext.length < 40) {
            hashtext = "0\$hashtext"
        }
        return hashtext
    }
}
KOTLIN;
    }

    /**
     * Generates the JpaUserDetailsService.kt file.
     * @return string
     */
    private function generateUserDetailsService()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.service

import $package.model.repository.AdminRepository
import org.springframework.security.core.userdetails.User
import org.springframework.security.core.userdetails.UserDetails
import org.springframework.security.core.userdetails.UserDetailsService
import org.springframework.security.core.userdetails.UsernameNotFoundException
import org.springframework.stereotype.Service

@Service
class JpaUserDetailsService(private val adminRepository: AdminRepository) : UserDetailsService {

    override fun loadUserByUsername(username: String): UserDetails {
        return adminRepository.findByUsername(username)
            .map { admin ->
                User.withUsername(admin.username)
                    .password(admin.password)
                    .roles("USER")
                    .build()
            }
            .orElseThrow { UsernameNotFoundException("User not found with username: \$username") }
    }
}
KOTLIN;
    }

    /**
     * Generates the Admin.kt entity file.
     * @return string
     */
    private function generateAdminEntity()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.model.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table

@Entity
@Table(name = "admin")
data class Admin(
    @Id
    @Column(name = "admin_id")
    var adminId: String? = null,
    var username: String? = null,
    var password: String? = null,
    var name: String? = null,
    var email: String? = null,
    var phone: String? = null,
    @Column(name = "admin_level_id")
    var adminLevelId: String? = null
)
KOTLIN;
    }

    /**
     * Generates the AdminRepository.kt file.
     * @return string
     */
    private function generateAdminRepository()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.model.repository

import $package.model.entity.Admin
import org.springframework.data.jpa.repository.JpaRepository
import java.util.Optional

interface AdminRepository : JpaRepository<Admin, String> {
    fun findByUsername(username: String): Optional<Admin>
}
KOTLIN;
    }

    /**
     * Generates the LoginRequest.kt DTO file.
     * @return string
     */
    private function generateLoginRequestDto()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.controller.dto

data class LoginRequest(
    val username: String,
    val password: String
)
KOTLIN;
    }

    /**
     * Generates the LoginResponse.kt DTO file.
     * @return string
     */
    private function generateLoginResponseDto()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.controller.dto

data class LoginResponse(
    val success: Boolean,
    val message: String
)
KOTLIN;
    }

    /**
     * Generates the AuthController.kt file.
     * @return string
     */
    private function generateAuthController()
    {
        $package = $this->projectConfig['packageName'];
        return <<<KOTLIN
package $package.controller

import $package.config.Sha1PasswordEncoder
import $package.controller.dto.LoginResponse
import $package.model.repository.AdminRepository
import jakarta.servlet.http.HttpServletRequest
import jakarta.servlet.http.HttpSession
import org.springframework.beans.factory.annotation.Value
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*

@RestController
class AuthController(
    private val adminRepository: AdminRepository,
    private val passwordEncoder: Sha1PasswordEncoder
) {

    @Value("\${app.security.require-login:true}")
    private val requireLogin: Boolean = true

    @PostMapping("/login")
    fun login(@RequestParam username: String, @RequestParam password: String, session: HttpSession): ResponseEntity<LoginResponse> {
        if (!requireLogin) {
            return ResponseEntity.ok(LoginResponse(true, "Success"))
        }

        val singleHashedPassword = passwordEncoder.sha1(password)
        val adminOptional = adminRepository.findByUsername(username)

        if (adminOptional.isPresent) {
            val admin = adminOptional.get()
            if (admin.password == passwordEncoder.encode(password)) {
                session.setAttribute("username", admin.username)
                session.setAttribute("password", singleHashedPassword) // Store single hash
                return ResponseEntity.ok(LoginResponse(true, "Login successful"))
            }
        }

        return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
            .body(LoginResponse(false, "Invalid credentials"))
    }

    @RequestMapping(value = ["/logout"], method = [RequestMethod.GET, RequestMethod.POST])
    fun logout(request: HttpServletRequest): ResponseEntity<LoginResponse> {
        if (!requireLogin) {
            return ResponseEntity.ok(LoginResponse(true, "Success"))
        }
        request.session.invalidate()
        return ResponseEntity.ok(LoginResponse(true, "Logout successful"))
    }
}
KOTLIN;
    }

    /**
     * Generates the gradlew.bat batch script for Windows.
     *
     * @return string The content of the gradlew.bat script.
     */
    private function generateGradleBat()
    {
        return <<<KOTLIN
@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem
@rem SPDX-License-Identifier: Apache-2.0
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME% 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:downloadWrapper
echo.
echo Downloading Gradle Wrapper Jar...

@rem Parse gradle-wrapper.properties to find the Gradle version from distributionUrl
setlocal
set WRAPPER_PROPERTIES="%APP_HOME%\gradle\wrapper\gradle-wrapper.properties"
for /f "tokens=1,2 delims==" %%a in ('findstr /i "distributionUrl" %WRAPPER_PROPERTIES%') do (
    if /i "%%a"=="distributionUrl" (
        set "DIST_URL=%%b"
    )
)

for /f "tokens=5 delims=/-" %%v in ("%DIST_URL%") do set GRADLE_VERSION=%%v
endlocal & set GRADLE_VERSION=%GRADLE_VERSION%

set WRAPPER_JAR_URL=https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/%GRADLE_VERSION%/gradle-wrapper-%GRADLE_VERSION%.jar
set WRAPPER_JAR_DIR=%APP_HOME%\gradle\wrapper
set WRAPPER_JAR_PATH=%WRAPPER_JAR_DIR%\gradle-wrapper.jar

echo Downloading from %WRAPPER_JAR_URL%
if not exist "%WRAPPER_JAR_DIR%" mkdir "%WRAPPER_JAR_DIR%"
powershell.exe -Command "Invoke-WebRequest -Uri %WRAPPER_JAR_URL% -OutFile %WRAPPER_JAR_PATH%"
goto execute

:execute
@rem Setup the command line

set CLASSPATH=


@rem Execute Gradle
if not exist "%APP_HOME%\gradle\wrapper\gradle-wrapper.jar" (
    goto downloadWrapper
)
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" -jar "%APP_HOME%\gradle\wrapper\gradle-wrapper.jar" %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
KOTLIN;
    }

    /**
     * Generates the gradlew shell script for POSIX systems.
     * @return string The content of the gradlew script.
     */
    private function generateGradle()
    {
        return <<<KOTLIN
#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

# ##########################################################################
#
#  Gradle startup script for UN*X
#
# ##########################################################################

# Attempt to set APP_HOME
# Resolve links: \$0 may be a link
PRG="\$0"
# Need this for relative symlinks.
while [ -h "\$PRG" ] ; do
    ls=`ls -ld "\$PRG"`
    link=`expr "\$ls" : '.*-> \(.*\)\$'`
    if expr "\$link" : '/.*' > /dev/null; then
        PRG="\$link"
    else
        PRG=`dirname "\$PRG"`"/\$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"\$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "\$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "\$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Find java.exe
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="\$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="\$JAVA_HOME/bin/java"
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

download_wrapper() {
    echo
    echo "Downloading Gradle Wrapper Jar..."

    WRAPPER_PROPERTIES="\$APP_HOME/gradle/wrapper/gradle-wrapper.properties"
    if [ -f "\$WRAPPER_PROPERTIES" ]; then
        DIST_URL=`grep -e "distributionUrl" "\$WRAPPER_PROPERTIES" | cut -d'=' -f2`
        # Extract version from URL, e.g. https://.../gradle-8.3-bin.zip
        GRADLE_VERSION=`echo "\$DIST_URL" | sed -n 's/.*-\([0-9.]*\(-[a-zA-Z0-9]*\)*\)-\(bin\|all\).zip/\1/p'`
    fi

    if [ -z "\$GRADLE_VERSION" ]; then
        # Fallback if parsing fails
        echo "Could not determine Gradle version from wrapper properties. Please run 'gradle wrapper' task."
        exit 1
    fi

    WRAPPER_JAR_URL="https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/\$GRADLE_VERSION/gradle-wrapper-\$GRADLE_VERSION.jar"
    WRAPPER_JAR_DIR="\$APP_HOME/gradle/wrapper"
    WRAPPER_JAR_PATH="\$WRAPPER_JAR_DIR/gradle-wrapper.jar"

    echo "Downloading from \$WRAPPER_JAR_URL"
    mkdir -p "\$WRAPPER_JAR_DIR"
    
    # Download using curl or wget
    if command -v curl >/dev/null 2>&1; then
        curl -L -o "\$WRAPPER_JAR_PATH" "\$WRAPPER_JAR_URL"
    elif command -v wget >/dev/null 2>&1; then
        wget -O "\$WRAPPER_JAR_PATH" "\$WRAPPER_JAR_URL"
    else
        echo "ERROR: Neither curl nor wget is available to download the wrapper."
        exit 1
    fi
}


# Execute Gradle

WRAPPER_JAR="\$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "\$WRAPPER_JAR" ]; then
    download_wrapper
fi

exec "\$JAVACMD" \
    \${DEFAULT_JVM_OPTS} \
    \${JAVA_OPTS} \
    \${GRADLE_OPTS} \
    "-Dorg.gradle.appname=\$APP_BASE_NAME" \
    -jar "\$WRAPPER_JAR" \
    "\$@"
KOTLIN;
    }

    /**
     * Generates the gradle-wrapper.properties file.
     * @return string The content of the gradle-wrapper.properties file.
     */
    private function generateGradleWrapper()
    {
        return <<<KOTLIN
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.14.3-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
KOTLIN;
    }
}